import type { Sprite } from './sprites';

/**
 * Eve's Garden's monsters, islands 2 to 7: forty-two hand-placed sprites. Islands 8 to 10 wear
 * remixes of these, built in `sprites.ts`.
 *
 * Kept apart from `sprites.ts` only for length — `SPRITES` spreads this in,
 * so every reader (the garden's scene, the Raid Gate's portrait,
 * `sprites.test.ts`) sees one table. Each key is the `SpriteKey` on a monster
 * in `game/HeartBeat.Game.Core/Data/Island<N>.cs`, and `sprites.test.ts` reads
 * those files so a renamed key fails a test rather than drawing a blank.
 *
 * The rules island 1 set hold on every island: friendly spirits, nobody's
 * character, and silhouettes that get heavier down the island. Stage 5 is the
 * breather and looks like one; the semi-boss touches both walls; the boss
 * fills the frame.
 */
export const ISLAND_SPRITES: Record<string, Sprite> = {
  // --- island 2: Kitchen Grove ---
  // Stage 1: Pipkin. A seed not yet sprouted, one leaf up and eyes wide - the
  // smallest thing in the kitchen garden.
  'pipkin': [
    '................',
    '................',
    '................',
    '........oo......',
    '.......olao.....',
    '......olaao.....',
    '.......ooo......',
    '.......oo.......',
    '.....oommoo.....',
    '....ommmmmmo....',
    '...omlmmmmmmo...',
    '...omommmomo....',
    '...ommmmmmmmo...',
    '....ommaammo....',
    '.....oooooo.....',
    '................',
  ],
  // Stage 2: Buzzbun. A round honey bun of a bee, striped, with two wings that
  // close over it when it shells up.
  'buzzbun': [
    '................',
    '...oo......oo...',
    '..olloo..oollo..',
    '..ollllooollllo.',
    '...ollloolllo...',
    '....oooooooo....',
    '...ommmmmmmmo...',
    '..omommmmmomoo..',
    '..ommmmmmmmmmo..',
    '..oaaaaaaaaaao..',
    '..ommmmaammmmo..',
    '..oaaaaaaaaaao..',
    '...ommmmmmmmo...',
    '....oommmmoo....',
    '......oooo......',
    '................',
  ],
  // Stage 3: Pepperwisp. A chilli with a curled stem, drawn tall and thin
  // because it is the island's quick one.
  'pepperwisp': [
    '.........oo.....',
    '........olo.....',
    '.......oloo.....',
    '......oooo......',
    '.....oaaaao.....',
    '....oaallaao....',
    '....oalolaao....',
    '....oaaaaaao....',
    '....oaaaaaao....',
    '.....oaaaaao....',
    '.....oaalaao....',
    '......oaaao.....',
    '......oaao......',
    '.......oao......',
    '........o.......',
    '................',
  ],
  // Stage 4, the semi-boss: Auntie Crumble. A whole pie, edge to edge, lattice
  // across the top and steam off it.
  'auntie-crumble': [
    '.....o...o......',
    '....o...o...o...',
    '.....o...o.o....',
    '................',
    '..oooooooooooo..',
    '.ollllllllllllo.',
    'olmolmolmolmolmo',
    'ollllllllllllllo',
    'olmoolmolmooolmo',
    'ollllllllllllllo',
    'ommmmmmmmmmmmmmo',
    'omaammmmmmmmaamo',
    'ommmmmmmmmmmmmmo',
    '.oommmmmmmmmmoo.',
    '...oooooooooo...',
    '................',
  ],
  // Stage 5, the breather: Rindroll. A wedge of melon on its side with its
  // seeds showing - light, open, easy.
  'rindroll': [
    '................',
    '................',
    '................',
    '................',
    '.oooooooooooooo.',
    '.ollllllllllllo.',
    '..olalllllalo...',
    '..ollloolllo....',
    '...olalllalo....',
    '....olllllo.....',
    '.....olalo......',
    '......olo.......',
    '.......o........',
    '................',
    '................',
    '................',
  ],
  // Stage 6, the elite: the Frostcrate Golem. The pantry's cold box standing
  // up, frost along the lid, on two stubby legs.
  'frostcrate': [
    '.oooooooooooooo.',
    'olalllalllallalo',
    'oooooooooooooooo',
    'ommmmmmmmmmmmmmo',
    'omoommmmmmmmoomo',
    'ommmmmmmmmmmmmmo',
    'omlllllllllllllo',
    'omlmmmmmmmmmmlmo',
    'omlmmmmaammmmlmo',
    'omlmmmmmmmmmmlmo',
    'omlllllllllllllo',
    'ommmmmmmmmmmmmmo',
    '.oooooooooooooo.',
    '..ommo....ommo..',
    '..ommo....ommo..',
    '..oooo....oooo..',
  ],
  // Stage 7, the boss: Mother Marzipan. Three tiers of cake crowned with
  // candles, filling the frame top to bottom.
  'mother-marzipan': [
    '..a...a..a...a..',
    '.oao.oao.oao.oao',
    '..o...o..o...o..',
    '...oooooooooo...',
    '...ollllllllo...',
    '...olollolollo..',
    '..oommmmmmmmoo..',
    '..omaamaamaamo..',
    '..ommmmoommmmo..',
    '.ooooooooooooooo',
    '.ollllllllllllo.',
    'olaalaalaalaalao',
    'ollllllllllllllo',
    'ommmmmmmmmmmmmmo',
    'ommmmmmmmmmmmmmo',
    '.oooooooooooooo.',
  ],

  // --- island 3: Focus Falls ---
  // Stage 1: Driplet. One splash off the falls, still mid-bounce, with the
  // ripple it left underneath.
  'driplet': [
    '................',
    '................',
    '.......o........',
    '......olo.......',
    '......olo.......',
    '.....ollmo......',
    '....olmmmmo.....',
    '....olommomo....',
    '....ommmmmmo....',
    '.....omaamo.....',
    '......oooo......',
    '................',
    '...oo......oo...',
    '.....oooooo.....',
    '................',
    '................',
  ],
  // Stage 2: Pebblenook. Three stepping stones stacked into somebody, the top
  // one wearing a patch of moss.
  'pebblenook': [
    '................',
    '................',
    '......oooo......',
    '.....oaaaao.....',
    '.....ollllo.....',
    '......oooo......',
    '....oommmmoo....',
    '...ommommommo...',
    '...ommmmmmmmo...',
    '....oooooooo....',
    '..oommmmmmmmoo..',
    '.omlmmmmmmmmmmo.',
    '.ommmmmaammmmmo.',
    '.ommmmmmmmmmmmo.',
    '..oooooooooooo..',
    '................',
  ],
  // Stage 3: Eddywhirl. A whirlpool with a face in the middle of it - the
  // first spiral, because it is the first one that spins you round.
  'eddywhirl': [
    '................',
    '....oooooooo....',
    '...ollllllllo...',
    '..olloooooollo..',
    '.ollo......ollo.',
    '.olo..oooo..olo.',
    '.olo.olllo..olo.',
    '.olo.olooo.olo..',
    '.olo.ollaao.olo.',
    '.olo..oooo..olo.',
    '.ollo......ollo.',
    '..olloooooollo..',
    '...ollllllllo...',
    '....oooooooo....',
    '................',
    '................',
  ],
  // Stage 4, the semi-boss: Pingwing. A bell with wings that will not stop
  // chiming - wing tip to wing tip across the frame.
  'pingwing': [
    '.......oo.......',
    '......oaao......',
    '.....oooooo.....',
    '....ollllllo....',
    'o..ollllllllo..o',
    'oo.olloollool.oo',
    'olo.olllllllo.lo',
    'ollloollllloollo',
    '.ollollllllollo.',
    '..olollllllolo..',
    '...ollllllllo...',
    '..olllllllllllo.',
    '..oaaaaaaaaaao..',
    '...oooooooooo...',
    '.......oao......',
    '........o.......',
  ],
  // Stage 5, the breather: Lilypad Imp. A little frog sat on a lily pad on the
  // quiet pool. Mostly pad.
  'lilypad-imp': [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....oo..oo.....',
    '....oloooolo....',
    '....ommmmmmo....',
    '....omoaaomo....',
    '.....ommmmo.....',
    '..oooooooooooo..',
    '.olllllllllllo..',
    'olllllllloolllo.',
    '.ollllllllllllo.',
    '..oooooooooooo..',
    '................',
  ],
  // Stage 6, the elite: the Gristmill Golem. A millwheel for a body, paddles
  // all the way round, set on a stone footing.
  'gristmill': [
    '......oooo......',
    '...oo.olmo.oo...',
    '..olooolmooolo..',
    '...oommmmmmoo...',
    '.oommmoooommmoo.',
    'olmmmo....ommmlo',
    '.ommo.oaao.ommo.',
    'olmmo.oaao.ommlo',
    '.ommmo....ommmo.',
    '..oommmoommmoo..',
    '.olooommmmooolo.',
    '...oo.olmo.oo...',
    '......oooo......',
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    '.oooooooooooooo.',
  ],
  // Stage 7, the boss: the Cascade Warden. The whole top of the falls with a
  // face and a crown of spray, poured edge to edge.
  'cascade-warden': [
    '.o..o..oo..o..o.',
    'oao.oaoaaoao.oao',
    '.oooooooooooooo.',
    'ollllllllllllllo',
    'ollmlllllllllmlo',
    'olllooollooolloo',
    'ollllllllllllllo',
    'olmllllaallllmlo',
    'olmlllllllllmllo',
    'ollmlllllllllmlo',
    'olmllmllllmllmlo',
    'ollmllmllmllmllo',
    'olmllmllllmllmlo',
    '.ommommmmommomo.',
    '..o.o.o..o.o.o..',
    '.o.o.o.oo.o.o.o.',
  ],

  // --- island 4: Joy Ridge ---
  // Stage 1: Chirplet. A round little songbird, beak open, one wing tucked -
  // small enough to hold.
  'chirplet': [
    '................',
    '................',
    '................',
    '......oooo......',
    '.....ommmmo.....',
    '....ommommmoo...',
    '....ommmmmoaao..',
    '...ommmmmmmoo...',
    '...omllllmmmo...',
    '...ollllllmmo...',
    '...olllllmmo....',
    '....ollllmo.....',
    '.....oooooo.....',
    '......o..o......',
    '.....oo..oo.....',
    '................',
  ],
  // Stage 2: Kitetail. A diamond kite with a face on it and bows down its
  // tail. It winds its string up to brace.
  'kitetail': [
    '.......oo.......',
    '......olmo......',
    '.....ollmmo.....',
    '....olllmmmo....',
    '...ollolmomo....',
    '..olllllmmmmo...',
    '...ollllmmmo....',
    '....olllmmo.....',
    '.....ollmo......',
    '......oo........',
    '.......o........',
    '......oao.......',
    '.......o........',
    '........o.......',
    '.......oao......',
    '........o.......',
  ],
  // Stage 3: Glimmerbug. A firefly with its tail lit, wings up, drawn upward
  // because it flits faster than you do.
  'glimmerbug': [
    '................',
    '..oo........oo..',
    '.ollo......ollo.',
    '.olllo....olllo.',
    '..olllooooollo..',
    '...oollmmlloo...',
    '.....ommmmo.....',
    '.....omoomo.....',
    '.....ommmmo.....',
    '......oooo......',
    '.....oaaaao.....',
    '....oaallaao....',
    '....oallllao....',
    '.....oaaaao.....',
    '......oooo......',
    '................',
  ],
  // Stage 4, the semi-boss: The Echo. A cave mouth that talks, rings of its
  // own voice spreading out to both walls.
  'the-echo': [
    '................',
    '...oooooooooo...',
    '..ommmmmmmmmmo..',
    '.ommmmmmmmmmmmo.',
    'ommommmmmmmmommo',
    'ommmmmmmmmmmmmmo',
    'ommmoooooooommmo',
    'ommo.l....l.ommo',
    'omo.l.l..l.l.omo',
    'omo.l......l.omo',
    'omo..l....l..omo',
    'omo...aaaa...omo',
    'omo..........omo',
    'omoooooooooooomo',
    'oooooooooooooooo',
    '................',
  ],
  // Stage 5, the breather: Puffball. A dandelion clock gone to seed - all
  // fluff, gaps straight through.
  'puffball': [
    '................',
    '.....o.o.o......',
    '...o.l.l.l.o....',
    '..o.l.....l.o...',
    '.o.l..ooo..l.o..',
    '...l.olllo.l....',
    '.o.l.oaoao.l.o..',
    '...l.olllo.l....',
    '.o.l..ooo..l.o..',
    '..o.l..o..l.o...',
    '...o.l.o.l.o....',
    '.....o.o.o......',
    '.......o........',
    '.......o........',
    '......ooo.......',
    '................',
  ],
  // Stage 6, the elite: the Cairn Keeper. A stack of summit stones that stood
  // up, arms of rock and a flat stone hat.
  'cairn-keeper': [
    '....oooooooo....',
    '...ommmmmmmmo...',
    '....oooooooo....',
    '.....ollllo.....',
    '....olollolo....',
    '.....ollllo.....',
    '..oooooooooooo..',
    '.omo.ommmmmo.omo',
    '.omooommmmmooomo',
    '.omo.ommaammo.o.',
    '..o..ommmmmmo...',
    '....oooooooooo..',
    '...ollllllllllo.',
    '...ollmllllmllo.',
    '...oooooooooooo.',
    '................',
  ],
  // Stage 7, the boss: Mother Merriweather. A storm cloud with the sun stuck
  // behind it and the rain in her hair - frame top to bottom.
  'merriweather': [
    '..o.o.o..o.o.o..',
    '...oaaaooaaaao..',
    '..oaaaaaaaaaaao.',
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    'ommmmmmmmmmmmmmo',
    'ommmoommmmoommmo',
    'ommmmmmmmmmmmmmo',
    'ommmmmoaaommmmmo',
    'ommmmmmmmmmmmmmo',
    '.oommmmmmmmmmoo.',
    '...oooooooooo...',
    '.o..o..o..o..o..',
    'olo.olo.olo.olo.',
    '.o..o..o..o..o..',
    '..o..o..o..o..o.',
  ],

  // --- island 5: Rest Haven ---
  // Stage 1: Glowmoth. A lantern moth, wings wide and a little frayed, a lit
  // spot on each.
  'glowmoth': [
    '................',
    '................',
    '................',
    '.....o....o.....',
    '......o..o......',
    '..ooo.oooo.ooo..',
    '.ollloommoollo..',
    '.olaalommolaalo.',
    '.olllloommollll.',
    '..olllommmollo..',
    '...oooommoooo...',
    '.....olmmlo.....',
    '......oooo......',
    '................',
    '................',
    '................',
  ],
  // Stage 2: Shellsnooze. A snail curled most of the way into a spiral shell,
  // which is where it goes to brace.
  'shellsnooze': [
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....ommmmmmo....',
    '...ommoooommo...',
    '...omo.oo.omo...',
    '...omo.olo.omo..',
    '...ommo..oomo...',
    '....ommmmmmo.o.o',
    '.oooooooooooooo.',
    'olllllllllolollo',
    'ollllllllllllllo',
    '.oooooooooooooo.',
    '................',
    '................',
  ],
  // Stage 3: Steepling. A teapot with a face and steam off the spout, far too
  // strong and a little too hot.
  'steepling': [
    '.........o.o....',
    '........o.o.....',
    '......oooo......',
    '.....ollllo.....',
    '...oooooooooo...',
    '..ommmmmmmmmmo..',
    '.omommmmmmomomoo',
    'omommmmmmmmmoolo',
    'omommmaammmmoolo',
    'omommmmmmmmmoo..',
    '.oommmmmmmmmo...',
    '..ollllllllo....',
    '...oooooooo.....',
    '................',
    '................',
    '................',
  ],
  // Stage 4, the semi-boss: the Midnight Clock. A clock face in a tower, both
  // hands on twelve, pendulum hung below.
  'midnight-clock': [
    '......oooo......',
    '.....ommmmo.....',
    '....ommmmmmo....',
    '..oooooooooooo..',
    '.olllllllllllo..',
    'ollollloollollo.',
    'olllllolllllllo.',
    'ollollloallollo.',
    'olllllllllllllo.',
    'ollolllllllollo.',
    '.olllllllllllo..',
    '..oooooooooooo..',
    '..ommmmmmmmmmo..',
    '..ommmmoammmmo..',
    '..ommmmoammmmo..',
    '..oooooooooooo..',
  ],
  // Stage 5, the breather: Fluffkin. A pillow with a face, squashed flat in
  // the middle where someone has lain on it.
  'fluffkin': [
    '................',
    '................',
    '................',
    '................',
    '.o............o.',
    '.oooooooooooooo.',
    '.ollllllllllllo.',
    'olllloollolllllo',
    '.ollllllllllllo.',
    '.olllllaallllo..',
    '.ollllllllllllo.',
    '.oooooooooooooo.',
    '.o............o.',
    '................',
    '................',
    '................',
  ],
  // Stage 6, the elite: the Anvil Golem. An anvil for a torso, still glowing
  // where it was struck, on a heavy block.
  'anvil-golem': [
    '................',
    'oooooooooooooo..',
    'ommmmmmmmmmmmmoo',
    'ommoommmmmoommmo',
    '.ommmmmmmmmmmoo.',
    '..ommmaaaammmo..',
    '...ommmmmmmmo...',
    '....ommmmmmo....',
    '....ommmmmmo....',
    '...ommmmmmmmo...',
    '..oooooooooooo..',
    '.ollllllllllllo.',
    '.ollllllllllllo.',
    '.oooooooooooooo.',
    '..ommo....ommo..',
    '..oooo....oooo..',
  ],
  // Stage 7, the boss: Lady Lullaby. A crescent moon in a long nightcap, stars
  // caught on the tassel, top to bottom.
  'lady-lullaby': [
    '..............o.',
    '.............oao',
    '......ooooooo.o.',
    '....oommmmmmmo..',
    '...ommmmmmoo....',
    '..ollllloo......',
    '.olllllo........',
    '.ollolllo.......',
    'olllllllo...o...',
    'olllaalllo.oao..',
    'ollllllllloo.o..',
    '.olllllllllloo..',
    '.olllllllllllo..',
    '..oolllllllloo..',
    '....oooooooo....',
    '................',
  ],

  // --- island 6: Tandem Tides ---
  // Stage 1: Clamlet. A clam open just a crack, two eyes looking out of the
  // gap.
  'clamlet': [
    '................',
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '...oollllllo....',
    '..ollmllmllloo..',
    '.olmllmllmlllo..',
    '.oooooooooooooo.',
    '.o..o......o..o.',
    '.oooooooooooooo.',
    '.ommmmmmmmmmmmo.',
    '..ommmmmmmmmmo..',
    '...oommmmmmoo...',
    '.....oooooo.....',
    '................',
  ],
  // Stage 2: Starfin. A starfish up on two of its arms, the other three spread
  // to brace against the tide.
  'starfin': [
    '.......oo.......',
    '......olmo......',
    '......olmo......',
    '.....ollmmo.....',
    'oooooollmmoooooo',
    'ollllllllmmmmmmo',
    '.olllolllomommo.',
    '..ollllllmmmmo..',
    '...olllaammmo...',
    '...ollllmmmmo...',
    '..ollloo.oommmo.',
    '..ollo....ommo..',
    '.ollo......ommo.',
    '.olo........omo.',
    '.oo..........oo.',
    '................',
  ],
  // Stage 3: Kelpkin. A clump of kelp with a face in it, fronds reaching up -
  // the first tall thing on the shore.
  'kelpkin': [
    '..o......o...o..',
    '.olo....olo.olo.',
    '.olo...olo..olo.',
    '..olo..olo.olo..',
    '..olo.olo..olo..',
    '...ololo..olo...',
    '...oooooooooo...',
    '..ommmmmmmmmmo..',
    '..omoommmoomo...',
    '..ommmmmmmmmmo..',
    '..ommmaaammmmo..',
    '...ommmmmmmmo...',
    '...omo.omo.omo..',
    '...omo.omo.omo..',
    '...ooo.ooo.ooo..',
    '................',
  ],
  // Stage 4, the semi-boss: the Lamp Keeper. A lighthouse with its lamp lit
  // and its beam thrown both ways to the walls.
  'lamp-keeper': [
    '......oooo......',
    '.....oaaaao.....',
    'aaaa.oaaaao.aaaa',
    '....oooooooo....',
    '.....olmmlo.....',
    '.....oooooo.....',
    '.....olmmlo.....',
    '....olmmmmlo....',
    '....oaaaaaao....',
    '....olmoommo....',
    '....olmmmmmo....',
    '...oaaaaaaaao...',
    '...olmmmmmmmo...',
    '...olmmmmmmmo...',
    '.oooooooooooooo.',
    'oooooooooooooooo',
  ],
  // Stage 5, the breather: Crablet. A small crab going sideways, claws up,
  // mostly legs and air.
  'crablet': [
    '................',
    '................',
    '................',
    '.oo..........oo.',
    'olao........oalo',
    '.oo..........oo.',
    '..o..........o..',
    '...o.oooooo.o...',
    '....ommmmmmo....',
    '....omommomo....',
    '.o.oommmmmmoo.o.',
    '..o.o.o..o.o.o..',
    '.o.o........o.o.',
    '................',
    '................',
    '................',
  ],
  // Stage 6, the elite: the Barnacle Golem. A piece of old hull that stood up,
  // barnacles along the planks, porthole for a face.
  'barnacle-golem': [
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    'omlomlmmmmlmolmo',
    'ommmmmmmmmmmmmmo',
    'oooooooooooooooo',
    'ommmmoooooommmmo',
    'ommmolllllommmmo',
    'ommmoloolloommmo',
    'ommmolllllommmmo',
    'ommmmoooooommmmo',
    'oooooooooooooooo',
    'omlommlmmlmmolmo',
    'ommmmmmmmmmmmmmo',
    '.ommmo....ommmo.',
    '.ommmo....ommmo.',
    '.ooooo....ooooo.',
  ],
  // Stage 7, the boss: Queen Coralie. A reef grown into a queen, branches for
  // a crown and pearls strung between them.
  'queen-coralie': [
    'o..o..o..o..o..o',
    'oloolooloolooloo',
    '.olo.olo.olo.olo',
    '..olloollolloo..',
    '...oaoaoaoaoa...',
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    'ommoommmmmmoommo',
    'ommmmmmmmmmmmmmo',
    'ommmmmoaaommmmmo',
    '.ommmmmmmmmmmmo.',
    '..oommmmmmmmoo..',
    '.olloommmmoollo.',
    'ollllooooooolllo',
    'ollllllllllllllo',
    '.oooooooooooooo.',
  ],

  // --- island 7: Heartwood Summit ---
  // Stage 1: Rootling. A knot of root with one shoot up top, just out of the
  // soil - the smallest thing on the tree.
  'rootling': [
    '................',
    '................',
    '................',
    '.......oo.......',
    '......olao......',
    '.......oo.......',
    '.......oo.......',
    '.....oommoo.....',
    '....ommmmmmo....',
    '....omommomo....',
    '....ommmmmmo....',
    '.....ommmmo.....',
    '....o.oooo.o....',
    '...o.o....o.o...',
    '..o..........o..',
    '................',
  ],
  // Stage 2: Acornet. An acorn under its cap, which it pulls down over its
  // eyes to brace.
  'acornet': [
    '................',
    '................',
    '.......oo.......',
    '.......oo.......',
    '....oooooooo....',
    '...olmlmlmlmo...',
    '..olmlmlmlmlmo..',
    '..oooooooooooo..',
    '...ommmmmmmmo...',
    '...omommmmomo...',
    '...ommmmmmmmo...',
    '...ommmaammmo...',
    '....ommmmmmo....',
    '.....ommmmo.....',
    '......oooo......',
    '................',
  ],
  // Stage 3: Sapsprite. A bead of amber sap on its way down the bark, drawn
  // upward and quick like the island's other thirds.
  'sapsprite': [
    '.......oo.......',
    '......oaao......',
    '......oaao......',
    '.....oaalao.....',
    '.....oaalao.....',
    '....oaaalaao....',
    '....oaoaaoao....',
    '...oaaaaaaaao...',
    '...oaaaaaaaao...',
    '...oaalllaaao...',
    '....oaaaaaao....',
    '.....oaaaao.....',
    '......oooo......',
    '................',
    '................',
    '................',
  ],
  // Stage 4, the semi-boss: the Twin Oak. Two trunks grown into one, canopy
  // wall to wall and a split down the middle.
  'twin-oak': [
    '..oooooo.oooooo.',
    '.ollllllolllllo.',
    'ollmlllllllmlllo',
    'ollllllllllllllo',
    'ollllmlllllllmlo',
    '.oollllllllllo..',
    '...oooooooooo...',
    '....omo..omo....',
    '....omo..omo....',
    '....omoooomo....',
    '....ommoommo....',
    '....omooomoo....',
    '....ommmmmmo....',
    '...ommaaammmo...',
    '..oommmmmmmmoo..',
    '.oooooooooooooo.',
  ],
  // Stage 5, the breather: Leaflit. A single leaf on the wind, the vein down
  // it and nothing else.
  'leaflit': [
    '................',
    '................',
    '................',
    '...........oo...',
    '.........oollo..',
    '.......oolllo...',
    '......olllllo...',
    '.....ollllolo...',
    '....olllloll....',
    '....olllolo.....',
    '...ollloooo.....',
    '...ollool.......',
    '...oooo.........',
    '..o.............',
    '.o..............',
    '................',
  ],
  // Stage 6, the elite: the Heartwood Golem. A section of trunk on two root
  // legs, the growth rings for a chest.
  'heartwood-golem': [
    '...oooooooooo...',
    '..ollllllllllo..',
    '.olloooooooollo.',
    '.ollo.aaaa.ollo.',
    '.ollo......ollo.',
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    'ommmmoooooommmmo',
    'ommmolllllommmmo',
    'ommmololllommmmo',
    'ommmolllllommmmo',
    'ommmmoooooommmmo',
    '.ommmmmmmmmmmmo.',
    '..omo.o..o.omo..',
    '.omo..o..o..omo.',
    '.oo..oo..oo..oo.',
  ],
  // Stage 7, the boss: the Heartwood Crown. The top of the whole tree,
  // crowned, with a heart set in the trunk - the last thing in the garden
  // fills all of it.
  'heartwood-crown': [
    '.o.o.o.oo.o.o.o.',
    'oaoaoaoaaoaoaoao',
    'oooooooooooooooo',
    'ollllllllllllllo',
    'ollmllllllllmllo',
    'olllooollooolloo',
    'ollllllllllllllo',
    '.ollllllllllllo.',
    '..oooooooooooo..',
    '.....ommmmo.....',
    '....omaoaomo....',
    '....omaaaamo....',
    '.....omaamo.....',
    '....ommmmmmo....',
    '..oommmmmmmmoo..',
    '.oooooooooooooo.',
  ],
};

/**
 * Islands 8 to 10: twenty-one more hand-placed sprites.
 *
 * These used to be island 4, 2 and 3's drawings turned round and re-coloured by
 * `remix` in `sprites.ts`. They are now their own drawings: each is its young
 * self with the body's mid and light tones traded (the same spirit in the
 * evening) and its own gold details placed by hand - a crest or a halo, tassels
 * where it has room to hang them, a few lines of age on the face. The painted
 * pixel count only ever goes up from the original, so the weight rules
 * `sprites.test.ts` holds (boss heavier than stage one, the breather lighter
 * than the semi-boss) carry over from the island each one grew from.
 *
 * Keys are the `SpriteKey`s in `Data/Island8.cs` to `Data/Island10.cs`, in
 * stage order.
 */
export const ELDER_SPRITES: Record<string, Sprite> = {
  // --- island 8, Elder Highlands: island 4's spirits grown old ---
  // Stage 1: chirplet, grown old.
  'chirplet-elder': [
    '................',
    '.......a........',
    '......a.a.......',
    '......oooo......',
    '.....ollllo.....',
    '....ollollloo...',
    '....ollllloaao..',
    '...olollloloo...',
    '...olmmmmlllo...',
    '...ommmmmmllo...',
    '...ommmmmllo....',
    '....ommmmlo.....',
    '.....oooooo.....',
    '......oaao......',
    '.....oo..oo.....',
    '................',
  ],
  // Stage 2: kitetail, grown old.
  'kitetail-elder': [
    '.......ao.......',
    '...a..omlo..a...',
    '.....ommllo.....',
    '....oommlloo....',
    '...ommomlolo....',
    '..ammmmmlllloa..',
    '...ommomlolo....',
    '....ommmllo.....',
    '.....ommlo......',
    '......oo........',
    '.......o........',
    '......oao.......',
    '.......o........',
    '........o.......',
    '.......oao......',
    '........o.......',
  ],
  // Stage 3: glimmerbug, grown old.
  'glimmerbug-elder': [
    '................',
    '..oo........oo..',
    '.ommo......ommo.',
    '.ommmo.aa.ommmo.',
    '..ammmooooomma..',
    '...oommllmmoo...',
    '.....ollllo.....',
    '.....oloolo.....',
    '.....ollllo.....',
    '......oooo......',
    '.....ooaaoo.....',
    '....oaammaao....',
    '....oammmmao....',
    '.....oaaaao.....',
    '......oaao......',
    '.....a....a.....',
  ],
  // Stage 4: the echo, grown old.
  'the-echo-elder': [
    '....a..aa..a....',
    '...oooooooooo...',
    '..ollllllllllo..',
    '.ollllllllllllo.',
    'ollollllllllollo',
    'ollllllllllllllo',
    'allloooooooollla',
    'ollo.m....m.ollo',
    'olo.m.m..m.m.olo',
    'olo.m......m.olo',
    'olo..m....m..olo',
    'olo...alaa...olo',
    'olo...l.al...olo',
    'oloooooooooooolo',
    'oooooooooooooooo',
    '................',
  ],
  // Stage 5: puffball, grown old.
  'puffball-elder': [
    '.......a........',
    '...a.o.o.o..a...',
    '...o.m.m.m.o....',
    '..o.m.....m.o...',
    '.o.m..ooo..m.o..',
    '.a.m.ommmo.m..a.',
    '.o.m.oaoao.m.o..',
    '...m.ommmo.m....',
    '.o.m..lol..m.o..',
    '..o.m..o..m.o...',
    '...o.m.o.m.o....',
    '.....o.o.o......',
    '.......o........',
    '.......o........',
    '......aoa.......',
    '.......a........',
  ],
  // Stage 6: cairn keeper, grown old.
  'cairn-keeper-elder': [
    '...aooooooooa...',
    '...ollllllllo...',
    '....oooooooo....',
    '.....omaamo.....',
    '....omommomo....',
    '.a...ommmmo...a.',
    '..oooooooooooo..',
    '.olo.olllllo.olo',
    '.olooolllllooolo',
    '.olo.ollaallo.o.',
    '..o..ollllllo...',
    '....oooooooooo..',
    '...ommmmmmmmmmo.',
    '...ommlmmmmlmmo.',
    '...ooooaaoooooo.',
    '.....a....a.....',
  ],
  // Stage 7: merriweather, grown old.
  'merriweather-elder': [
    '..o.o.oaao.o.o..',
    '...oaaaooaaaao..',
    '..oaaaaaaaaaaao.',
    '..oooooooooooo..',
    '.ollllllllllllo.',
    'ollllllllllllllo',
    'ollloolllloolllo',
    'ollllllllllllllo',
    'ollllloaaolllllo',
    'olllllollolllllo',
    '.oolllllllllloo.',
    'a..oooooooooo..a',
    '.o..o..o..o..o..',
    'oao.omo.omo.oma.',
    '.o..o..o..o..o..',
    '..o..o..o..o..o.',
  ],
  // --- island 9, Elder Kitchen Grove: island 2's spirits grown old ---
  // Stage 1: pipkin, grown old.
  'pipkin-elder': [
    '................',
    '................',
    '.....a.aa.a.....',
    '......a.oa......',
    '.......omao.....',
    '......omaao.....',
    '.......ooo......',
    '.......oo.......',
    '.....oolloo.....',
    '....ollllllo....',
    '...oomllllllo...',
    '...ololllolo....',
    '...ollllllllo...',
    '....ollaallo....',
    '.....oooooo.....',
    '.....aa..aa.....',
  ],
  // Stage 2: buzzbun, grown old.
  'buzzbun-elder': [
    '....a..aa..a....',
    '...oo......oo...',
    '..ommoo..oommo..',
    '..ommmmooommmmo.',
    '...ommmoommmo...',
    '....oooooooo....',
    '.a.ollllllllo.a.',
    '..olollllloloo..',
    '..ollllllllllo..',
    '..oaaaaaaaaaao..',
    '..ollllaallllo..',
    '..oaaaaaaaaaao..',
    '...ollllllllo...',
    '....oolllloo....',
    '......oooo......',
    '.......aa.......',
  ],
  // Stage 3: pepperwisp, grown old.
  'pepperwisp-elder': [
    '......a..oo.....',
    '.......aomo.....',
    '.......omoo.....',
    '...a..oooo..a...',
    '.....oaaaao.....',
    '....oaammaao....',
    '....oamomaao....',
    '....oaaaaaao....',
    '...aoaaaaaaoa...',
    '.....oaaaaao....',
    '.....oaamaao....',
    '......oaaao.....',
    '......oaao......',
    '.....a.oaoa.....',
    '.......ao.......',
    '................',
  ],
  // Stage 4: auntie crumble, grown old.
  'auntie-crumble-elder': [
    '.....o...o......',
    '....o..aa...o...',
    '.....o...o.o....',
    '.....a....a.....',
    '..oooooooooooo..',
    '.ommmmmmmmmmmmo.',
    'oalomlomlomlomao',
    'ommmmmmmmmmmmmmo',
    'omloomlomlooomlo',
    'ommmmmmmmmmmmmmo',
    'ollllllllllllllo',
    'olaallllllllaalo',
    'ollllllllllllllo',
    '.oolllllllllloo.',
    '...aooooooooa...',
    '......a..a......',
  ],
  // Stage 5: rindroll, grown old.
  'rindroll-elder': [
    '................',
    '................',
    '.......aa.......',
    '......a..a......',
    '.oooooooooooooo.',
    '.ommmmmmmmmmmmo.',
    '..omammmmmamo...',
    '.aommmoommmo..a.',
    '...omammmamo....',
    '...aommmmmo.a...',
    '.....omamo......',
    '......omo.......',
    '.......o........',
    '.......aa.......',
    '................',
    '................',
  ],
  // Stage 6: frostcrate, grown old.
  'frostcrate-elder': [
    '.oooooooooooooo.',
    'omammmammmammamo',
    'oooooooaaooooooo',
    'ollllllllllllllo',
    'oloolllllllloolo',
    'ollllllllllllllo',
    'olmmmmmmmmmmmmmo',
    'olmllllllllllmlo',
    'olmllllaallllmlo',
    'olmllllllllllmlo',
    'olmmmmmmmmmmmmmo',
    'ollllllllllllllo',
    '.oooooloolooooo.',
    '..ollo....ollo..',
    '..ollo.aa.ollo..',
    '..aooo....oooa..',
  ],
  // Stage 7: mother marzipan, grown old.
  'mother-marzipan-elder': [
    '..aa..a..a..aa..',
    '.oao.oaaaoao.oao',
    '..o...o..o...o..',
    '...oooooooooo...',
    '...ommmmmmmmo...',
    '.a.omommomommoa.',
    '..oolllllllloo..',
    '..olaalaalaalo..',
    '..olllloollllo..',
    '.ooooooooooooooo',
    '.ommmmmmmmmmmmo.',
    'omaamaamaamaamao',
    'ommmmammmmammmmo',
    'ollllllllllllllo',
    'ollallllllllallo',
    '.oooooooooooooo.',
  ],
  // --- island 10, Zenith Falls: island 3's spirits grown old ---
  // Stage 1: driplet, grown old.
  'driplet-elder': [
    '................',
    '.......a........',
    '....a..o...a....',
    '......omo.......',
    '......omo.......',
    '.....ommlo......',
    '...aomllllo.a...',
    '....omollolo....',
    '....ollllllo....',
    '.....olaalo.....',
    '......oooo......',
    '.....a.a..a.....',
    '...oo......oo...',
    '.....oooooo.....',
    '.......aa.......',
    '................',
  ],
  // Stage 2: pebblenook, grown old.
  'pebblenook-elder': [
    '.......aa.......',
    '....a......a....',
    '......oooo......',
    '.....oaaaao.....',
    '.....ommmmo.....',
    '......oooo......',
    '....oolllloo....',
    '...ollollollo...',
    '.a.ollllllllo.a.',
    '....oooooooo....',
    '..oolllllllloo..',
    '.olmllllllllllo.',
    '.olllllaalllllo.',
    '.ollllllllllllo.',
    '..oooooooooooo..',
    '....a.a..a.a....',
  ],
  // Stage 3: eddywhirl, grown old.
  'eddywhirl-elder': [
    '.......aa.......',
    '....oooooooo....',
    '...ommmmmmmmo...',
    '..ommoooooommo..',
    '.ommo..aa..ommo.',
    '.omo..oooo..omo.',
    '.omo.ommmo..omo.',
    'aomo.omooo.omo.a',
    '.omo.ommaao.omo.',
    '.omo..oooo..omo.',
    '.ommo......ommo.',
    '..ommoooooommo..',
    '...ommmmmmmmo...',
    '....oooooooo....',
    '....a..aa..a....',
    '................',
  ],
  // Stage 4: pingwing, grown old.
  'pingwing-elder': [
    '......aooa......',
    '......oaao......',
    '.....oooooo.....',
    '.a..ommmmmmo..a.',
    'o..ommmmmmmmo..o',
    'oo.ommoommoom.oo',
    'omo.ommmmmmmo.mo',
    'ommmoommmmmoommo',
    '.ommommmmmmommo.',
    'a.omommmmmmomo..',
    '...ommmmmmmmo...',
    '..ommmommommmmo.',
    '..oaaaaaaaaaao..',
    '...aooooooooa...',
    '.......aao......',
    '........o.......',
  ],
  // Stage 5: lilypad imp, grown old.
  'lilypad-imp-elder': [
    '................',
    '................',
    '................',
    '.......aa.......',
    '....a.a..a.a....',
    '.....oo..oo.....',
    '....omoooomo....',
    '....ollllllo....',
    '....oloaaolo....',
    '.....ollllo.....',
    '..oooooooooooo..',
    '.ommmmmmmmmmmo..',
    'ommmmmmmmoommmo.',
    '.ommmmmmmmmmmmo.',
    '..oooooooooooo..',
    '...a...a....a...',
  ],
  // Stage 6: gristmill, grown old.
  'gristmill-elder': [
    '.....aooooa.....',
    '...oo.omlo.oo...',
    '.aomooomlooomoa.',
    '...oolllllloo...',
    '.oollloooollloo.',
    'omlllo....olllmo',
    '.ollo.oaao.ollo.',
    'omllo.oaao.ollmo',
    '.olllo....olllo.',
    '..oollloollloo..',
    '.omooollllooomo.',
    '...oo.omlo.oo...',
    '......oooo......',
    '..oooooooooooo..',
    '.ollallaallallo.',
    '.ooooooaaoooooo.',
  ],
  // Stage 7: cascade warden, grown old.
  'cascade-warden-elder': [
    '.o..oa.oo.ao..o.',
    'oao.oaoaaoao.oao',
    '.oooooolloooooo.',
    'ommmmmmmmmmmmmmo',
    'ommlmmmmmmmmmlmo',
    'ommmooommooommoo',
    'ommmmmmmmmmmmmmo',
    'amlmmmmaammmmlma',
    'omlmmmmmmmmmlmmo',
    'ommlmmmmmmmmmlmo',
    'omlmmlmmmmlmmlmo',
    'ommlmmlmmlmmlmmo',
    'omlmmlmmmmlmmlmo',
    '.ollollllollolo.',
    '..oao.oaao.oao..',
    '.o.o.o.oo.o.o.o.',
  ],
};


/** The sprite keys of islands 2-7, in stage order. */
export const ISLAND_SPRITE_ORDER: Record<number, readonly string[]> = {
  2: ['pipkin', 'buzzbun', 'pepperwisp', 'auntie-crumble', 'rindroll', 'frostcrate', 'mother-marzipan'],
  3: ['driplet', 'pebblenook', 'eddywhirl', 'pingwing', 'lilypad-imp', 'gristmill', 'cascade-warden'],
  4: ['chirplet', 'kitetail', 'glimmerbug', 'the-echo', 'puffball', 'cairn-keeper', 'merriweather'],
  5: ['glowmoth', 'shellsnooze', 'steepling', 'midnight-clock', 'fluffkin', 'anvil-golem', 'lady-lullaby'],
  6: ['clamlet', 'starfin', 'kelpkin', 'lamp-keeper', 'crablet', 'barnacle-golem', 'queen-coralie'],
  7: ['rootling', 'acornet', 'sapsprite', 'twin-oak', 'leaflit', 'heartwood-golem', 'heartwood-crown'],
};
