import { deck } from './deck';

/**
 * Data structures and complexity. The interview deck, but chosen for the parts
 * that actually change decisions rather than the parts that are trivia.
 */
export const bigoDeck = deck(
  'bigo',
  'Data structures & Big-O',
  'What each structure costs, and when the constant wins.',
  [
    {
      id: 'bigo-what',
      question: 'What does Big-O actually describe?',
      answer: 'An upper bound on how cost grows as input grows — not the time taken.',
      why: 'It deliberately discards constants and lower-order terms, which is why an O(n) algorithm can be slower than an O(n²) one on real input sizes. It answers "what happens when this gets big", and nothing else.',
      difficulty: 'easy',
    },
    {
      id: 'bigo-constants',
      question: 'When does the constant factor matter more than the complexity class?',
      answer: 'At small n, and whenever cache locality is involved.',
      why: 'Insertion sort beats quicksort below roughly a dozen elements, which is why real sort implementations switch to it at the bottom. An array scan often beats a hash lookup for small collections because it is contiguous in memory.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-array-vs-list',
      question: 'Array or linked list for a queue of a million items?',
      answer: 'Almost always the array-backed structure — a ring buffer.',
      why: 'Linked lists have textbook O(1) insertion but every node is a pointer chase into unpredictable memory, and a cache miss costs a hundred-odd cycles. Contiguous memory is why the "worse" complexity usually wins in practice.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-hash-average',
      question: 'What is hash table lookup, average and worst case?',
      answer: 'O(1) average, O(n) worst when everything collides.',
      why: 'The worst case is not theoretical: attacker-chosen keys that all hash to one bucket are a real denial-of-service vector, which is why runtimes seed their hash functions randomly. Modern implementations also fall back to a tree per bucket.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-amortised',
      question: 'What does amortised O(1) mean for appending to a dynamic array?',
      answer: 'Most appends are O(1); occasionally one is O(n) to resize, and the average over many is constant.',
      why: 'Doubling the capacity means the expensive copies get rarer exactly as fast as they get more expensive. Note it says nothing about the worst single operation — which matters in real-time or latency-sensitive code.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-binary-search',
      question: 'What must be true before binary search is valid, and what does it cost?',
      answer: 'The data must already be sorted. O(log n).',
      why: 'The trap is sorting in order to binary search once — that is O(n log n) to save on an O(n) scan. Sorting pays off only when you will search many times, or need the order anyway.',
      difficulty: 'easy',
    },
    {
      id: 'bigo-sort-lower-bound',
      question: 'Why can no comparison sort beat O(n log n)?',
      answer: 'There are n! orderings and each comparison yields one bit, so log₂(n!) ≈ n log n comparisons are needed.',
      why: 'It is an information-theoretic bound, not a failure of imagination. Counting and radix sorts beat it precisely because they do not compare — they use the structure of the keys, and pay for it with assumptions about the key space.',
      difficulty: 'hard',
    },
    {
      id: 'bigo-stable-sort',
      question: 'What does a stable sort guarantee, and when do you need it?',
      answer: 'Equal elements keep their relative order. You need it when sorting by one key after another.',
      why: 'Sort by name, then stably by department, and within each department names remain ordered. With an unstable sort the first pass is destroyed. JavaScript\'s `sort` has been required to be stable since ES2019.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-quicksort-worst',
      question: 'What is quicksort\'s worst case and how is it avoided?',
      answer: 'O(n²) on an adversarial or already-sorted input with a naive pivot. Avoided with a randomised or median-of-three pivot.',
      why: 'Choosing the first element as pivot makes sorted input the worst case, which is exactly the input that turns up most often. Introsort switches to heapsort once recursion goes too deep, capping the worst case at O(n log n).',
      difficulty: 'hard',
    },
    {
      id: 'bigo-heap',
      question: 'What is a heap good for, and what does it cost?',
      answer: 'Repeatedly taking the smallest or largest item. O(1) peek, O(log n) insert and extract.',
      why: 'It is the right structure for a priority queue, a scheduler, and the top-k problem — where keeping a heap of size k gives O(n log k) instead of sorting everything at O(n log n).',
      difficulty: 'medium',
    },
    {
      id: 'bigo-bst-balance',
      question: 'Why does an unbalanced binary search tree degrade to a linked list?',
      answer: 'Inserting sorted data makes every node a right child, so depth becomes n and lookups O(n).',
      why: 'Self-balancing variants — red-black, AVL, B-trees — exist entirely to prevent this. It is why database indexes are B-trees: they guarantee depth, and their wide nodes match the size of a disk page.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-btree-index',
      question: 'Why are database indexes B-trees rather than binary trees?',
      answer: 'Each node holds hundreds of keys and fills one page, so a lookup costs three or four disk reads instead of thirty.',
      why: 'When the unit of cost is a page fetch rather than a comparison, minimising tree height is everything. A binary tree of a million rows is twenty levels deep; a B-tree is three.',
      difficulty: 'hard',
    },
    {
      id: 'bigo-trie',
      question: 'What problem is a trie the right answer to?',
      answer: 'Prefix queries — autocomplete, routing tables, dictionary membership.',
      why: 'Lookup is O(length of the key), independent of how many keys are stored. The cost is memory, which is why real implementations compress runs of single-child nodes into a radix tree.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-two-pointer',
      question: 'What does the two-pointer technique buy you on a sorted array?',
      answer: 'It turns many O(n²) nested-loop problems into O(n).',
      why: 'For "find a pair summing to a target", move the left pointer up when the sum is too small and the right down when too big. Each pointer moves at most n times. The related sliding window does the same for subarray problems.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-memoisation',
      question: 'How does memoisation change naive recursive Fibonacci?',
      answer: 'From O(2ⁿ) to O(n), by never recomputing a subproblem.',
      why: 'That is the whole of dynamic programming: overlapping subproblems plus a cache. Top-down memoisation and bottom-up tabulation are the same idea; the bottom-up version avoids the call stack and is usually faster.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-space-time',
      question: 'What is the space complexity of the common "count occurrences with a hash map" approach?',
      answer: 'O(k) for k distinct values — often the trade that buys the time improvement.',
      why: 'Worth stating explicitly in an interview and in review: converting an O(n²) scan to O(n) usually costs O(n) memory. On a stream too large to hold, that trade is not available and you need a sketch instead.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-set-membership',
      question: 'Why is `array.includes` inside a loop a classic performance bug?',
      answer: 'It is O(n) per call, so the loop is O(n²). A Set makes it O(1) per call.',
      why: 'It is the single most common accidental quadratic in application code, and it is invisible in testing because it only bites at scale. Building the Set costs one pass.',
      difficulty: 'easy',
    },
    {
      id: 'bigo-string-concat',
      question: 'Why is building a string by repeated concatenation in a loop dangerous?',
      answer: 'In languages with immutable strings each concatenation copies the whole thing, making it O(n²).',
      why: 'Collect the pieces in an array and join once. Some runtimes optimise this with ropes or in-place growth, but relying on that is relying on an implementation detail.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-bfs-dfs',
      question: 'When do you choose BFS over DFS?',
      answer: 'When you need the shortest path in an unweighted graph, or the answer is likely near the start.',
      why: 'BFS visits in order of distance, so the first time it reaches the target is by a shortest route. DFS uses less memory on wide graphs and is natural for exhaustive search, topological ordering and cycle detection.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-dijkstra',
      question: 'What does Dijkstra require that BFS does not, and what breaks it?',
      answer: 'Weighted edges and a priority queue. Negative edge weights break it.',
      why: 'It commits to a node\'s distance when it pops it, which a later negative edge could invalidate. Bellman-Ford handles negatives at O(V·E); A* adds a heuristic to Dijkstra to explore fewer nodes.',
      difficulty: 'hard',
    },
    {
      id: 'bigo-lru',
      question: 'What two structures does an LRU cache need, and why?',
      answer: 'A hash map for O(1) lookup and a doubly linked list for O(1) reordering and eviction.',
      why: 'Neither alone works: the map cannot track recency, and the list cannot find an entry quickly. The map stores node references into the list. It is the classic "combine two structures" interview question and a genuinely common piece of code.',
      difficulty: 'hard',
    },
    {
      id: 'bigo-bloom',
      question: 'What does a Bloom filter tell you, and what is the catch?',
      answer: 'Definitely-not-present or maybe-present, in tiny constant space. False positives, never false negatives.',
      why: 'Perfect as a cheap gate before an expensive lookup — a disk read, a network call. Standard Bloom filters also cannot delete, which is what counting variants address.',
      difficulty: 'hard',
    },
    {
      id: 'bigo-tail-call',
      question: 'Why can deep recursion crash where an equivalent loop does not?',
      answer: 'Each call consumes a stack frame, and the stack is small and fixed.',
      why: 'Tail-call optimisation would fix it but most runtimes — including every major JavaScript engine except JavaScriptCore — do not implement it. Recursion depth proportional to input size is a latent crash.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-n-plus-one',
      question: 'What is an N+1 query problem?',
      answer: 'One query fetches N rows, then a query per row fetches its related data — N+1 round trips.',
      why: 'The most common performance bug in any ORM-backed application, because the code that causes it looks like an innocent loop over a relation. The fixes are eager loading with a join, or one batched IN query.',
      difficulty: 'medium',
    },
    {
      id: 'bigo-profile-first',
      question: 'What is the first thing to do about a slow program?',
      answer: 'Measure it. Intuition about where the time goes is reliably wrong.',
      why: 'Optimising the wrong 90% costs time and adds complexity for nothing. A profiler routinely shows the cost sitting somewhere nobody suspected — serialisation, logging, an accidental quadratic in a helper.',
      difficulty: 'easy',
    },
  ],
);
