import { deck } from './deck';

/**
 * Git, taught as a model rather than a list of commands. Almost every confusing
 * thing about it stops being confusing once you know it is a graph of snapshots
 * and the branches are just labels.
 */
export const gitDeck = deck(
  'git',
  'Git',
  'The object model, and how to get out of trouble.',
  [
    {
      id: 'git-commit-is',
      question: 'What is a commit, physically?',
      answer: 'A snapshot of the whole tree, plus a pointer to its parent, author, message, and a hash of all of it.',
      why: 'Git does not store diffs. Diffs are computed on demand between two snapshots. Because the hash covers the parent, changing any commit changes every commit after it — which is why rewriting history gives you new hashes.',
      difficulty: 'medium',
    },
    {
      id: 'git-branch-is',
      question: 'What is a branch?',
      answer: 'A movable file containing one commit hash. Nothing more.',
      why: 'This is why branching is instant and free — it writes 41 bytes. It also explains why deleting a branch does not delete commits: it removes a label, and the commits stay until garbage collection cannot reach them from any label.',
      difficulty: 'easy',
    },
    {
      id: 'git-head',
      question: 'What is HEAD?',
      answer: 'A pointer to the branch you are on — or, when detached, directly to a commit.',
      why: 'Detached HEAD means commits you make have no branch pointing at them, so moving away loses them from normal view. They are still findable in the reflog until garbage collection, which is what makes the state recoverable rather than fatal.',
      difficulty: 'easy',
    },
    {
      id: 'git-three-trees',
      question: 'What are the three places a file can be?',
      answer: 'The working directory, the index (staging area), and the last commit (HEAD).',
      why: 'Nearly every git command is a way of moving changes between those three. `add` copies working to index; `commit` copies index to HEAD; `checkout` copies the other way. Knowing which two a command touches predicts what it will destroy.',
      difficulty: 'easy',
    },
    {
      id: 'git-reset-modes',
      question: 'What is the difference between `reset --soft`, `--mixed` and `--hard`?',
      answer: 'Soft moves the branch only; mixed also resets the index; hard also overwrites the working directory.',
      why: 'Mixed is the default. Hard is the only one that can lose uncommitted work, and it is the one command in ordinary use that genuinely destroys data — everything else can be recovered from the reflog.',
      difficulty: 'medium',
    },
    {
      id: 'git-revert-vs-reset',
      question: 'When do you revert rather than reset?',
      answer: 'When the commit is already pushed and other people have it.',
      why: 'Revert makes a new commit that undoes the change, so history is append-only and nobody else has to do anything. Reset rewrites history, which forces everyone downstream to reconcile — fine on your own unpushed branch, rude on a shared one.',
      difficulty: 'easy',
    },
    {
      id: 'git-merge-vs-rebase',
      question: 'What is the practical difference between merge and rebase?',
      answer: 'Merge records that two lines came together; rebase replays your commits onto a new base, giving new hashes and a straight line.',
      why: 'Merge preserves what actually happened, at the cost of a knotted graph. Rebase produces a history that reads as a story, at the cost of it being a story. The usual rule: rebase your own unpushed work, merge anything shared.',
      difficulty: 'medium',
    },
    {
      id: 'git-golden-rule',
      question: 'What is the golden rule of rebasing?',
      answer: 'Never rebase commits that exist in someone else\'s repository.',
      why: 'Rebasing replaces commits with new ones. Anyone who had the originals now has both, and merging the two sets duplicates every commit. On a shared branch the fix is a merge; on your own feature branch, rebase freely.',
      difficulty: 'medium',
    },
    {
      id: 'git-fast-forward',
      question: 'What is a fast-forward merge?',
      answer: 'When the target branch is a direct ancestor, git just moves the label forward — no merge commit.',
      why: '`--no-ff` forces a merge commit anyway, which keeps the shape of a feature branch visible in the graph. Teams argue about this; the honest summary is that it trades a noisier graph for the ability to see and revert a feature as a unit.',
      difficulty: 'medium',
    },
    {
      id: 'git-reflog',
      question: 'What is the reflog, and when does it save you?',
      answer: 'A local log of every position HEAD has held. It recovers commits no branch points at any more.',
      why: 'After a bad reset, a botched rebase, or a deleted branch, `git reflog` shows the hash you were on and `git reset --hard <hash>` puts you back. It is local-only and expires by default after 90 days, so it is a safety net, not a backup.',
      difficulty: 'medium',
    },
    {
      id: 'git-stash',
      question: 'What does `git stash` do, and what does it miss by default?',
      answer: 'Saves tracked modifications and clears the working tree. It ignores untracked and ignored files unless you pass `-u` or `-a`.',
      why: 'The default is the cause of the classic "my new file was not stashed and then got clobbered". `git stash -u` includes untracked files. Stashes are also easy to forget about — they are a queue, not a branch.',
      difficulty: 'easy',
    },
    {
      id: 'git-cherry-pick',
      question: 'What does `git cherry-pick` do?',
      answer: 'Applies the change from one commit as a new commit on your current branch.',
      why: 'Useful for pulling one hotfix out of a branch that is not ready. The new commit has a different hash, so cherry-picking and later merging the source branch can present the same change twice — usually harmless, occasionally a conflict.',
      difficulty: 'medium',
    },
    {
      id: 'git-fetch-vs-pull',
      question: 'What is the difference between `fetch` and `pull`?',
      answer: 'Fetch downloads and updates the remote-tracking branches. Pull is fetch followed by a merge or rebase into your branch.',
      why: 'Fetch is always safe — it never touches your working tree, so it cannot conflict. Pull can. Fetching first and looking at what arrived, then integrating deliberately, is the habit that avoids most surprise merges.',
      difficulty: 'easy',
    },
    {
      id: 'git-force-with-lease',
      question: 'Why prefer `--force-with-lease` over `--force`?',
      answer: 'It refuses the push if the remote moved since you last fetched, so you cannot silently erase someone else\'s work.',
      why: 'Plain `--force` overwrites the remote branch regardless of what is there. With-lease checks that the remote is where you think it is first. On a branch you share with anyone, it is the only acceptable force.',
      difficulty: 'medium',
    },
    {
      id: 'git-detached-recover',
      question: 'You committed on a detached HEAD and checked out main. How do you keep the work?',
      answer: 'Find the hash in `git reflog` and `git branch <name> <hash>`.',
      why: 'The commits were never lost — they simply had nothing pointing at them. Creating a branch at that hash makes them reachable again. This works until garbage collection prunes unreachable objects, which is not immediate.',
      difficulty: 'medium',
    },
    {
      id: 'git-interactive-rebase',
      question: 'What can an interactive rebase do?',
      answer: 'Reorder, edit, squash, fixup, drop or reword any commit in a range.',
      why: 'It is how a messy branch of fourteen "wip" commits becomes three that explain themselves before review. All of it rewrites hashes, so the golden rule applies — do it before you share, not after.',
      difficulty: 'medium',
    },
    {
      id: 'git-bisect',
      question: 'What does `git bisect` do?',
      answer: 'Binary-searches the history for the commit that introduced a bug, given a known-good and known-bad commit.',
      why: 'It turns "somewhere in the last 500 commits" into about nine checkouts. With `git bisect run <script>` that exits non-zero on failure, it finds the culprit unattended — the highest-leverage git command almost nobody uses.',
      difficulty: 'hard',
    },
    {
      id: 'git-blame-w',
      question: 'Why is `git blame` often useless on a reformatted file, and what fixes it?',
      answer: 'A formatting commit rewrites every line. `-w` ignores whitespace, and `--ignore-rev` skips a named commit.',
      why: 'A repo can also list bulk-reformat commits in `.git-blame-ignore-revs` so every blame skips them by default. Without that, the entire file is attributed to whoever ran the formatter.',
      difficulty: 'hard',
    },
    {
      id: 'git-merge-conflict',
      question: 'What does a merge conflict actually mean?',
      answer: 'Both sides changed the same region since the common ancestor, so git will not guess.',
      why: 'Git merges by three-way comparison against the merge base, not by comparing the two tips. That is why a change on one side alone applies cleanly however large it is, and why two one-character edits on the same line conflict.',
      difficulty: 'medium',
    },
    {
      id: 'git-gitignore-tracked',
      question: 'Why does adding a file to `.gitignore` not stop it being committed?',
      answer: 'Ignore rules only apply to untracked files. An already-tracked file keeps being tracked.',
      why: 'You need `git rm --cached <file>` to stop tracking it, then commit that removal. This is the usual reason a `.env` keeps appearing in diffs after someone "fixed it in gitignore" — and if it was ever pushed, the secret is in history and must be rotated.',
      difficulty: 'medium',
    },
    {
      id: 'git-tag-vs-branch',
      question: 'How does a tag differ from a branch?',
      answer: 'A tag is a label that does not move; a branch advances with each commit.',
      why: 'Tags mark releases. An annotated tag is a real object with a message, tagger and optional signature; a lightweight tag is just a pointer. Tags are also not pushed by default — `git push --tags` or push the ref explicitly.',
      difficulty: 'easy',
    },
    {
      id: 'git-squash-merge',
      question: 'What does a squash merge do to future merges from that branch?',
      answer: 'It creates one new commit unrelated to the branch\'s commits, so the branch appears unmerged and re-merging replays everything.',
      why: 'The tidy single commit on main shares no ancestry with the feature commits. The convention that goes with squash merging is to delete the branch immediately and never merge from it again.',
      difficulty: 'hard',
    },
    {
      id: 'git-amend',
      question: 'What does `git commit --amend` actually do?',
      answer: 'Replaces the last commit with a new one — new hash, new content, same parent.',
      why: 'Nothing is edited in place; the old commit is orphaned and sits in the reflog. That is why amending a pushed commit needs a force push, and why amending is safe on work you have not shared.',
      difficulty: 'easy',
    },
    {
      id: 'git-worktree',
      question: 'What problem does `git worktree` solve?',
      answer: 'Checking out a second branch into a separate directory sharing one repository, with no stashing and no second clone.',
      why: 'Perfect for reviewing a PR or running a long build while you keep working. It shares the object store, so it costs a working copy rather than a full clone, and each worktree has its own index and HEAD.',
      difficulty: 'hard',
    },
    {
      id: 'git-shallow-clone',
      question: 'What does `git clone --depth 1` trade away?',
      answer: 'History. You get the tip only, so log, blame, bisect and merge-base are unavailable or wrong.',
      why: 'Right for CI, where the checkout is disposable and the clone time matters. Wrong for a working copy, and a common cause of CI jobs that cannot diff against a base branch until the fetch depth is increased.',
      difficulty: 'medium',
    },
  ],
);
