import { deck } from './deck';

/**
 * HTTP and the web platform — the layer every application sits on and most
 * bugs eventually turn out to be about.
 */
export const httpDeck = deck(
  'http',
  'HTTP & the web',
  'Status codes, caching, CORS, cookies, auth.',
  [
    {
      id: 'http-idempotent',
      question: 'What does it mean for a method to be idempotent, and which ones are?',
      answer: 'Repeating it has the same effect as doing it once. GET, HEAD, PUT and DELETE are; POST and PATCH are not.',
      why: 'It is what makes a retry safe. A network timeout leaves you not knowing whether the request landed — with an idempotent method you just send it again. With POST you need an idempotency key, which is why payment APIs all have one.',
      difficulty: 'medium',
    },
    {
      id: 'http-put-patch',
      question: 'What is the difference between PUT and PATCH?',
      answer: 'PUT replaces the whole resource; PATCH applies a partial change.',
      why: 'The practical consequence is that a PUT missing a field should clear that field, not leave it alone. Most APIs that call it PUT actually implement PATCH semantics, which is a reliable source of "why did my other field disappear".',
      difficulty: 'easy',
    },
    {
      id: 'http-401-403',
      question: 'What is the difference between 401 and 403?',
      answer: '401 means not authenticated — who are you? 403 means authenticated but not permitted.',
      why: 'A 401 invites the client to supply credentials and should carry a `WWW-Authenticate` header. A 403 says credentials will not help. Sending 401 for a permission failure sends clients into a pointless re-login loop.',
      difficulty: 'easy',
    },
    {
      id: 'http-404-vs-403',
      question: 'When is returning 404 for a forbidden resource the right call?',
      answer: 'When the existence of the resource is itself confidential.',
      why: 'A 403 confirms the thing exists, which leaks information — an attacker can enumerate valid ids by the difference between 403 and 404. Deliberately returning 404 removes the oracle at the cost of a slightly confusing error.',
      difficulty: 'hard',
    },
    {
      id: 'http-422',
      question: 'What does 422 mean, and how is it different from 400?',
      answer: '400 is malformed — the server could not parse it. 422 parsed fine but failed validation.',
      why: 'Useful to distinguish because they need different client behaviour: a 400 is a bug in your request construction, a 422 is something to show the user next to a form field.',
      difficulty: 'medium',
    },
    {
      id: 'http-429',
      question: 'What should a client do on a 429?',
      answer: 'Back off, honouring `Retry-After` if present, ideally with exponential backoff plus jitter.',
      why: 'Jitter matters as much as backoff: without it every rate-limited client retries at the same instant and the thundering herd re-limits everyone. Retrying immediately on 429 is the fastest way to get banned outright.',
      difficulty: 'medium',
    },
    {
      id: 'http-301-302',
      question: 'Why is a 301 dangerous to issue casually?',
      answer: 'It is permanent, and browsers cache it aggressively — sometimes indefinitely.',
      why: 'A mistaken 301 can persist in users\' browsers long after the server is fixed, and there is no way to reach out and clear it. Use 302 or 307 while you are unsure; 308 and 307 additionally preserve the method and body, which 301 and 302 historically did not.',
      difficulty: 'medium',
    },
    {
      id: 'http-cache-control',
      question: 'What does `Cache-Control: no-cache` actually mean?',
      answer: 'Store it, but revalidate with the server before reusing it. `no-store` is the one that means do not keep it.',
      why: 'This naming trips up nearly everyone. `no-cache` still writes to disk, so it is not sufficient for sensitive data — that needs `no-store`. And `private` means "browser may cache, shared proxies may not".',
      difficulty: 'medium',
    },
    {
      id: 'http-etag',
      question: 'How does an ETag save bandwidth?',
      answer: 'The client sends it back in `If-None-Match`; an unchanged resource gets a 304 with no body.',
      why: 'Conditional requests still cost a round trip but not the payload. `Last-Modified`/`If-Modified-Since` does the same with a timestamp, which is coarser — one-second resolution and clock-dependent.',
      difficulty: 'medium',
    },
    {
      id: 'http-immutable-assets',
      question: 'Why are hashed asset filenames paired with a one-year cache?',
      answer: 'The content cannot change without the filename changing, so the cache never needs invalidating.',
      why: 'Cache invalidation is avoided rather than solved. The HTML that references them stays uncached or short-cached, so a deploy changes one small document and every large asset is either already held or fetched once, forever.',
      difficulty: 'medium',
    },
    {
      id: 'http-cors-what',
      question: 'What is CORS actually protecting?',
      answer: 'It stops a script on one origin reading a response from another, unless that origin opts in.',
      why: 'It does not stop the request being sent — the server may already have acted on it. CORS is a read restriction enforced by the browser, which is why it protects users from malicious pages and never protects a server from anything.',
      difficulty: 'medium',
    },
    {
      id: 'http-preflight',
      question: 'What triggers a CORS preflight?',
      answer: 'Anything beyond a simple request: a method other than GET/HEAD/POST, a custom header, or a non-form content type such as application/json.',
      why: 'This is why sending JSON with an Authorization header always costs an extra OPTIONS round trip. `Access-Control-Max-Age` lets the browser cache the preflight result and skip it for subsequent calls.',
      difficulty: 'hard',
    },
    {
      id: 'http-cors-credentials',
      question: 'Why does `Access-Control-Allow-Origin: *` fail once credentials are involved?',
      answer: 'With credentials the spec forbids the wildcard — the server must echo the specific origin and send `Allow-Credentials: true`.',
      why: 'Otherwise any site could make authenticated requests with the user\'s cookies and read the answer. Echoing the origin means you must validate it against an allowlist, not reflect whatever arrived.',
      difficulty: 'hard',
    },
    {
      id: 'http-samesite',
      question: 'What does `SameSite=Lax` on a cookie do?',
      answer: 'Sends the cookie on top-level navigations to your site but not on cross-site subrequests.',
      why: 'It is CSRF protection built into the cookie, and now the browser default. `Strict` also withholds it on inbound links, which logs users out when they arrive from elsewhere. `None` sends it always and requires `Secure`.',
      difficulty: 'medium',
    },
    {
      id: 'http-httponly',
      question: 'What does `HttpOnly` protect against, and what does it not?',
      answer: 'It hides the cookie from JavaScript, so XSS cannot exfiltrate it. It does nothing against CSRF.',
      why: 'The two defences solve different attacks: HttpOnly stops the token being stolen, SameSite and CSRF tokens stop it being used from another site. A session cookie wants both, plus `Secure`.',
      difficulty: 'medium',
    },
    {
      id: 'http-jwt-storage',
      question: 'Why is storing a JWT in localStorage contentious?',
      answer: 'Any XSS on the page can read it, and unlike a cookie it cannot be marked HttpOnly.',
      why: 'The usual counter is that cookies bring CSRF — but SameSite largely answers that, whereas nothing answers "script on my page can read my token". An HttpOnly, Secure, SameSite cookie is the more defensible default.',
      difficulty: 'hard',
    },
    {
      id: 'http-jwt-revoke',
      question: 'What is the fundamental limitation of a JWT for sessions?',
      answer: 'It is self-validating, so you cannot revoke one before it expires without keeping server state.',
      why: 'That trades away the very thing that made it appealing. The usual compromise: short-lived access tokens plus a revocable refresh token, so a logout takes effect within minutes rather than instantly or never.',
      difficulty: 'hard',
    },
    {
      id: 'http-https-protects',
      question: 'What does HTTPS protect, and what does it still leak?',
      answer: 'It encrypts the URL path, headers and body. It leaks the destination IP, and the hostname via SNI and DNS.',
      why: 'So an observer knows you visited a site but not which page. This is also why "the query string is encrypted" is true on the wire yet irrelevant — the URL still lands in server logs, browser history, and Referer headers.',
      difficulty: 'medium',
    },
    {
      id: 'http-content-type',
      question: 'Why does a missing or wrong `Content-Type` cause such odd bugs?',
      answer: 'Servers pick a parser from it, and browsers may sniff the type of a response and treat it as something else.',
      why: 'A JSON body sent as text/plain may reach the handler unparsed. On responses, MIME sniffing can turn an uploaded file into executable HTML — which is what `X-Content-Type-Options: nosniff` exists to prevent.',
      difficulty: 'medium',
    },
    {
      id: 'http-keepalive',
      question: 'What did HTTP/1.1 keep-alive and then HTTP/2 multiplexing each solve?',
      answer: 'Keep-alive reuses one TCP connection for several requests; HTTP/2 sends many requests concurrently over one connection.',
      why: 'Keep-alive removed the handshake per request but kept head-of-line blocking within the connection. HTTP/2 interleaves streams, which is why domain sharding and sprite sheets became counterproductive rather than clever.',
      difficulty: 'hard',
    },
    {
      id: 'http-post-redirect-get',
      question: 'What problem does the Post/Redirect/Get pattern solve?',
      answer: 'Refreshing after a form POST re-submits it. Redirecting to a GET makes refresh harmless.',
      why: 'It is why a successful form usually answers 303 and a new URL rather than rendering the result directly. It also makes the result page bookmarkable and gives the back button sane behaviour.',
      difficulty: 'easy',
    },
    {
      id: 'http-rest-statelessness',
      question: 'What does it mean that REST is stateless?',
      answer: 'Every request carries everything needed to serve it; the server keeps no per-client conversation state.',
      why: 'It is what lets any instance behind a load balancer answer any request, which is the whole basis of horizontal scaling. Server-side sessions are the common compromise, and the reason they get pushed into Redis rather than memory.',
      difficulty: 'medium',
    },
    {
      id: 'http-pagination',
      question: 'Why does cursor pagination beat `OFFSET` for large or live datasets?',
      answer: 'Offset re-scans everything skipped and shifts when rows are inserted, so pages overlap or skip items.',
      why: 'A cursor keyed on an indexed, ordered column seeks straight to the position and is stable under inserts. Offset stays fine for small, static result sets and for jumping to an arbitrary page number.',
      difficulty: 'hard',
    },
    {
      id: 'http-websocket-sse',
      question: 'When is Server-Sent Events the better choice over a WebSocket?',
      answer: 'When the data only flows server to client. SSE is plain HTTP and reconnects automatically.',
      why: 'It rides existing infrastructure, works through most proxies, and the browser handles retry and last-event-id resumption for you. WebSockets earn their extra complexity when the client also needs to push, frequently and with low latency.',
      difficulty: 'medium',
    },
    {
      id: 'http-timeouts',
      question: 'Why does a service without client timeouts fail worse than one with them?',
      answer: 'Requests pile up waiting on a slow dependency until connections and threads are exhausted, turning one slow service into a total outage.',
      why: 'This is cascading failure, and a timeout is the cheapest defence — it converts "hangs forever" into "fails fast", which a retry or circuit breaker can then handle. The default in most HTTP clients is no timeout at all.',
      difficulty: 'hard',
    },
  ],
);
