import { deck } from './deck';

/**
 * JavaScript, and specifically the parts that surprise people who already know
 * another language. Not syntax — semantics, where the bugs live.
 */
export const jsDeck = deck(
  'js',
  'JavaScript',
  'Coercion, scope, this, and the event loop.',
  [
    {
      id: 'js-typeof-null',
      question: 'What does `typeof null` return, and why?',
      answer: '"object" — a bug from 1995 that can never be fixed.',
      why: 'Values were tagged by their low bits; the object tag was 000, and null was the null pointer, all zeroes. It reads as an object tag. Fixing it would break the web, so it stays. Use `value === null` to test for null.',
      difficulty: 'easy',
    },
    {
      id: 'js-equality',
      question: 'When should you use `==` instead of `===`?',
      answer: 'Effectively never, with one idiom: `x == null` matches both null and undefined.',
      why: '`==` applies coercion rules almost nobody has memorised, which is why `0 == ""` and `null == undefined` are both true while `null == 0` is false. The one place it earns its keep is the null check, because it catches undefined in the same breath.',
      difficulty: 'easy',
    },
    {
      id: 'js-nan',
      question: 'How do you test whether a value is NaN?',
      answer: '`Number.isNaN(x)`. Never `x === NaN`, and preferably not the global `isNaN`.',
      why: 'NaN is the only value not equal to itself, so `===` can never find it. The global `isNaN` coerces first, so `isNaN("hello")` is true — it answers "is this not a number", not "is this NaN". `Number.isNaN` does no coercion.',
      difficulty: 'easy',
    },
    {
      id: 'js-hoisting',
      question: 'What is the temporal dead zone?',
      answer: 'The span between a `let`/`const` binding being created and being initialised, where touching it throws a ReferenceError.',
      why: '`let` and `const` are hoisted like `var` — the binding exists from the top of the block — but unlike `var` they are not initialised to undefined. That gap is the dead zone. It turns a silent undefined into a loud error, which is the point.',
      difficulty: 'medium',
    },
    {
      id: 'js-closure',
      question: 'What is a closure?',
      answer: 'A function together with the scope it was defined in, kept alive as long as the function is.',
      why: 'Every function in JavaScript is a closure. It matters when the function outlives the call that made it — a callback, a returned function, an event handler — because the variables it captured are captured by reference, not copied.',
      difficulty: 'medium',
    },
    {
      id: 'js-loop-var',
      question: 'Why does a `var` loop counter print the final value in every `setTimeout`, while `let` prints each one?',
      answer: '`var` creates one binding for the whole function; `let` creates a fresh binding per iteration.',
      why: 'The classic interview question, and it is really about closures capturing by reference. With `var` all three callbacks close over the same variable, which is 3 by the time they run. `let` in a for-loop is specified to rebind each pass, so each callback closes over its own.',
      difficulty: 'medium',
    },
    {
      id: 'js-this',
      question: 'What determines the value of `this` in a normal function?',
      answer: 'How it is called, not where it is defined.',
      why: 'Called as `obj.fn()`, `this` is obj. Called bare, it is undefined in strict mode and globalThis otherwise. Called with `call`/`apply`/`bind`, it is whatever you passed. This is why extracting a method into a variable breaks it.',
      difficulty: 'medium',
    },
    {
      id: 'js-arrow-this',
      question: 'How is `this` different inside an arrow function?',
      answer: 'Arrows have no `this` of their own — they use the enclosing scope, decided where they are written.',
      why: 'That is why arrows are right for callbacks inside a method and wrong for object methods and prototypes: an arrow used as a method closes over the surrounding scope rather than the object it was called on.',
      difficulty: 'medium',
    },
    {
      id: 'js-event-loop',
      question: 'In what order do a `Promise.resolve().then()` and a `setTimeout(..., 0)` scheduled together run?',
      answer: 'The promise callback first. Microtasks drain completely before the next macrotask.',
      why: 'The event loop runs one macrotask (a timer, an I/O callback), then empties the entire microtask queue before the next. So promises always beat timers scheduled in the same tick — and an endless chain of microtasks can starve timers entirely.',
      difficulty: 'hard',
    },
    {
      id: 'js-await-loop',
      question: 'What is wrong with `await`-ing inside a `for` loop over independent requests?',
      answer: 'It serialises them. Ten 200ms requests take two seconds instead of 200ms.',
      why: 'Each `await` waits for that one before starting the next. When the work is independent, start it all and then wait: `await Promise.all(items.map(fetchOne))`. Keep the sequential loop only when each step genuinely needs the last one, or when you are deliberately rate-limiting.',
      difficulty: 'medium',
    },
    {
      id: 'js-promise-all-settled',
      question: 'When do you want `Promise.allSettled` over `Promise.all`?',
      answer: 'When one failure should not discard the successes.',
      why: '`Promise.all` rejects the moment any input rejects, and the results of the ones that succeeded are lost. `allSettled` always fulfils, with a status/value or status/reason per entry — right for a batch where partial success is still useful.',
      difficulty: 'medium',
    },
    {
      id: 'js-spread-shallow',
      question: 'What does `{ ...obj }` copy?',
      answer: 'One level. Nested objects and arrays are shared with the original, not cloned.',
      why: 'A shallow copy is usually what you want and occasionally a disaster — mutating `copy.address.city` also changes the original. For a real deep copy use `structuredClone(obj)`, which also handles Dates, Maps and cycles that JSON round-tripping destroys.',
      difficulty: 'easy',
    },
    {
      id: 'js-optional-chain',
      question: 'What does `a?.b.c` do if `a` is null?',
      answer: 'Returns undefined without evaluating the rest — the whole chain short-circuits.',
      why: 'A common misreading is that only the `?.` link is guarded and `.c` then throws. It does not: `?.` short-circuits everything to its right. Note this guards null and undefined only, not the empty string or 0.',
      difficulty: 'medium',
    },
    {
      id: 'js-nullish',
      question: 'How does `??` differ from `||` for defaults?',
      answer: '`??` only falls through on null and undefined; `||` falls through on every falsy value.',
      why: 'This is a real bug source: `count || 10` turns a legitimate 0 into 10, and `name || "anon"` turns an empty string into "anon". `??` gives the default only when the value is genuinely absent.',
      difficulty: 'easy',
    },
    {
      id: 'js-sort-default',
      question: 'What does `[10, 9, 1].sort()` return?',
      answer: '`[1, 10, 9]` — the default sort compares as strings.',
      why: 'Without a comparator, sort coerces every element to a string and compares by UTF-16 code units. For numbers you must pass one: `sort((a, b) => a - b)`. Note also that sort mutates the array; `toSorted` returns a new one.',
      difficulty: 'easy',
    },
    {
      id: 'js-array-holes',
      question: 'Why does `new Array(3).map((_, i) => i)` not produce `[0, 1, 2]`?',
      answer: 'It makes a sparse array of three holes, and `map` skips holes.',
      why: 'The array has length 3 but no elements, and the iteration methods walk actual keys. `Array.from({ length: 3 }, (_, i) => i)` works, and so does `Array(3).fill(0).map(...)` because `fill` writes real values first.',
      difficulty: 'medium',
    },
    {
      id: 'js-mutation-methods',
      question: 'Which common array methods mutate in place?',
      answer: 'push, pop, shift, unshift, splice, sort, reverse and fill.',
      why: 'The rest — map, filter, slice, concat — return new arrays. Mixing them up is how React state stops re-rendering: mutating an array in place leaves the reference identical, so nothing downstream can tell it changed.',
      difficulty: 'easy',
    },
    {
      id: 'js-object-key-order',
      question: 'What order do object keys iterate in?',
      answer: 'Integer-like keys first in ascending numeric order, then string keys in insertion order.',
      why: 'So `{ b: 1, 2: 2, a: 3 }` iterates 2, b, a. If insertion order genuinely matters — a cache, an ordered lookup — use a Map, which preserves it for every key type and does not stringify keys.',
      difficulty: 'hard',
    },
    {
      id: 'js-map-vs-object',
      question: 'When should you reach for a Map instead of a plain object?',
      answer: 'Keys that are not strings, keys that could collide with prototype names, frequent adds and deletes, or when you need the size.',
      why: 'Object keys are coerced to strings, so `obj[1]` and `obj["1"]` are the same slot, and a key called "constructor" or "__proto__" is a hazard. Map keeps key identity, has `.size`, and is optimised for churn.',
      difficulty: 'medium',
    },
    {
      id: 'js-json-loses',
      question: 'What does `JSON.parse(JSON.stringify(obj))` silently destroy?',
      answer: 'Dates become strings; undefined, functions and symbols vanish; Map, Set and BigInt break; cycles throw.',
      why: 'It is the traditional deep clone and it is lossy in ways that surface much later — a Date that is now a string usually fails at the first `.getTime()`. `structuredClone` handles all of these except functions.',
      difficulty: 'medium',
    },
    {
      id: 'js-float',
      question: 'Why is `0.1 + 0.2 === 0.3` false?',
      answer: 'IEEE-754 binary floating point cannot represent 0.1 or 0.2 exactly.',
      why: 'The sum is 0.30000000000000004. This is not a JavaScript flaw — it is every language with binary floats. Compare with a tolerance, or hold money as integer cents, or use a decimal library. Never store currency in a float.',
      difficulty: 'easy',
    },
    {
      id: 'js-label-generators',
      question: 'What does a generator function give you that a normal one does not?',
      answer: 'It can pause at each `yield` and resume where it left off, producing values lazily.',
      why: 'Useful for infinite or expensive sequences you do not want to materialise, for walking a tree without building the whole list, and as the machinery async/await was originally built on top of.',
      difficulty: 'hard',
    },
    {
      id: 'js-symbol-iterator',
      question: 'What makes an object work with `for...of` and the spread operator?',
      answer: 'A `[Symbol.iterator]` method returning an iterator.',
      why: 'This is why arrays, strings, Maps and Sets all spread but plain objects do not. Implementing it on your own class is what makes `[...myCollection]` work, and it is what `for...of` looks for — `for...in` is unrelated and walks enumerable string keys, including inherited ones.',
      difficulty: 'hard',
    },
    {
      id: 'js-debounce-throttle',
      question: 'What is the difference between debounce and throttle?',
      answer: 'Debounce waits for a pause before firing once; throttle fires at most once per interval during the activity.',
      why: 'Debounce a search box — you want the request after typing stops. Throttle a scroll or resize handler — you want steady updates while it happens, not one at the end.',
      difficulty: 'medium',
    },
    {
      id: 'js-error-async',
      question: 'Why does a `try`/`catch` around a call not catch an error thrown inside its `setTimeout` callback?',
      answer: 'The callback runs later, on a different stack — the try block is long gone.',
      why: 'try/catch is lexical and synchronous. The same applies to a promise you do not await: the rejection escapes. Handle errors where the async work actually completes, with `await` inside the try, or `.catch()`, or the callback\'s own guard.',
      difficulty: 'medium',
    },
  ],
);
