import { deck } from './deck';

/**
 * The craft rather than the syntax — testing, debugging, review, and the
 * judgement calls that separate code that works from code that keeps working.
 * The deck most likely to be useful five years after the others go stale.
 */
export const practiceDeck = deck(
  'practice',
  'Engineering practice',
  'Testing, debugging, review, and judgement.',
  [
    {
      id: 'prac-test-pyramid',
      question: 'What does the test pyramid argue?',
      answer: 'Many fast unit tests, fewer integration tests, very few end-to-end tests.',
      why: 'The shape follows from cost: an e2e test is slow, flaky and tells you something broke; a unit test is instant and tells you what. The inverted pyramid — mostly e2e — is a suite nobody runs and nobody trusts.',
      difficulty: 'easy',
    },
    {
      id: 'prac-test-behaviour',
      question: 'Why test behaviour rather than implementation?',
      answer: 'A test coupled to implementation fails on every refactor, so it punishes the changes you most want to make.',
      why: 'A suite that breaks when nothing observable changed trains people to update tests without reading them. Assert on what a caller can see — return values, side effects, rendered output — not on which private method was called.',
      difficulty: 'medium',
    },
    {
      id: 'prac-coverage',
      question: 'What does 100% test coverage prove?',
      answer: 'That every line executed. Not that any of it was checked.',
      why: 'A test with no assertions gets full coverage. Coverage is useful in the negative — it reliably finds untested code — and misleading as a target, because the cheapest way to raise it is to test what is easy rather than what is risky.',
      difficulty: 'medium',
    },
    {
      id: 'prac-flaky-test',
      question: 'What should you do with a flaky test?',
      answer: 'Fix it or delete it. Never retry it into passing.',
      why: 'A test that fails ten percent of the time trains the team to re-run the build, which means the day it catches a real bug nobody believes it. Flakiness is usually a real race in the code, not in the test.',
      difficulty: 'medium',
    },
    {
      id: 'prac-tdd-value',
      question: 'What does writing the test first actually buy you?',
      answer: 'A design forced through its own interface, and proof the test can fail.',
      why: 'A test written afterwards has never been seen to fail, so it might assert nothing. Writing it first also makes awkward APIs obvious immediately — if it is hard to test, it is hard to use.',
      difficulty: 'medium',
    },
    {
      id: 'prac-bug-first',
      question: 'What is the first step when fixing a reported bug?',
      answer: 'Reproduce it, then write a failing test that captures it.',
      why: 'Without reproduction you are guessing, and a "fix" you cannot verify is a change. The test also stops the bug returning — a regression is a bug someone already paid to find once.',
      difficulty: 'easy',
    },
    {
      id: 'prac-bisect-debug',
      question: 'What is the general strategy behind binary search debugging?',
      answer: 'Halve the space the fault can be in, repeatedly — in commits, in code, or in data.',
      why: 'It converts an unbounded hunt into a handful of checks. `git bisect` does it over history; commenting out half a config does it over configuration; truncating an input does it over data.',
      difficulty: 'medium',
    },
    {
      id: 'prac-rubber-duck',
      question: 'Why does explaining a bug out loud so often solve it?',
      answer: 'Explanation forces the assumptions to be stated, and one of them is wrong.',
      why: 'Debugging is nearly always finding the belief that is false rather than the line that is wrong. Anything that makes implicit assumptions explicit — writing it down, a colleague, a duck — attacks the actual problem.',
      difficulty: 'easy',
    },
    {
      id: 'prac-heisenbug',
      question: 'A bug disappears when you add logging. What does that suggest?',
      answer: 'A race condition or a timing dependency — the logging changed the timing.',
      why: 'Also possible: uninitialised memory, or an optimisation the extra code disabled. The category is "the observation changed the system", and it usually means the code depends on something it should be synchronising on.',
      difficulty: 'hard',
    },
    {
      id: 'prac-review-purpose',
      question: 'What is a code review actually for?',
      answer: 'Catching what tests cannot — unclear intent, wrong abstraction, missing cases — and spreading knowledge.',
      why: 'Style belongs to a formatter and correctness largely to tests. If review is mostly comments about spacing, the tooling is missing and the expensive human attention is being spent on the cheapest problem.',
      difficulty: 'easy',
    },
    {
      id: 'prac-small-prs',
      question: 'Why do small pull requests get better reviews?',
      answer: 'Review quality falls off a cliff with size — a large diff gets approved rather than read.',
      why: 'Comments per line drop sharply past a few hundred lines. Splitting a refactor from a behaviour change is the highest-value split there is, because then the diff that matters is small and the large one can be scanned.',
      difficulty: 'easy',
    },
    {
      id: 'prac-comment-why',
      question: 'What should a comment explain?',
      answer: 'Why, not what. The code already says what.',
      why: 'A comment restating the line is noise that goes stale. A comment recording why the obvious approach was rejected, or which bug a strange line prevents, is the thing that cannot be recovered by reading — and it saves the next person from "fixing" it.',
      difficulty: 'easy',
    },
    {
      id: 'prac-naming',
      question: 'Why is naming genuinely hard rather than a joke?',
      answer: 'A name is the interface to a concept — a wrong one makes every reader build the wrong model.',
      why: 'Difficulty naming something is usually the signal that it does not have one responsibility. The fix is often to split it, not to find a cleverer word.',
      difficulty: 'medium',
    },
    {
      id: 'prac-premature-abstraction',
      question: 'What is the cost of abstracting too early?',
      answer: 'An abstraction built from one example fits one case, and every later case bends it out of shape.',
      why: 'Duplication is cheaper than the wrong abstraction: duplicated code is easy to see and easy to merge later, whereas a wrong abstraction is threaded through everything. Wait for the third occurrence.',
      difficulty: 'medium',
    },
    {
      id: 'prac-yagni',
      question: 'What does YAGNI argue against?',
      answer: 'Building for requirements you have imagined rather than received.',
      why: 'Speculative generality costs complexity now for flexibility that usually turns out to be the wrong flexibility. The counterweight is that some decisions are genuinely expensive to reverse — those deserve thought up front.',
      difficulty: 'easy',
    },
    {
      id: 'prac-chesterton',
      question: 'What is Chesterton\'s Fence, applied to code?',
      answer: 'Do not remove something you do not understand the reason for, until you find the reason.',
      why: 'Odd-looking code is often a bug fix nobody documented. `git log -S` and `git blame` usually find the commit. If the reason has genuinely gone, delete it and say so in the message.',
      difficulty: 'medium',
    },
    {
      id: 'prac-idempotency',
      question: 'Why is idempotency the most valuable property in a distributed system?',
      answer: 'Because retries are unavoidable, and only idempotent operations are safe to retry.',
      why: 'Networks lose responses, not just requests — so the caller cannot know whether the work happened. Every reliable system is built out of operations that can be repeated without harm, usually via a deduplication key.',
      difficulty: 'hard',
    },
    {
      id: 'prac-at-least-once',
      question: 'Why is exactly-once delivery generally impossible?',
      answer: 'The acknowledgement can be lost, so the sender must choose between resending and not.',
      why: 'What is achievable is at-least-once delivery plus idempotent processing, which is exactly-once *effect*. Systems advertising exactly-once are almost always doing that internally.',
      difficulty: 'hard',
    },
    {
      id: 'prac-cap',
      question: 'What does the CAP theorem actually force you to choose between?',
      answer: 'Consistency and availability, but only while a network partition is happening.',
      why: 'It is widely misread as a permanent three-way choice. Partitions are rare and unavoidable; the real question is what your system does during one — refuse writes, or accept them and reconcile later.',
      difficulty: 'hard',
    },
    {
      id: 'prac-graceful-degradation',
      question: 'What does it mean to fail gracefully?',
      answer: 'Losing a non-essential dependency reduces functionality instead of taking the whole thing down.',
      why: 'Recommendations time out, so the page renders without them. This requires deciding in advance which dependencies are critical — a decision that is otherwise made accidentally by whichever call has no timeout.',
      difficulty: 'medium',
    },
    {
      id: 'prac-feature-flag',
      question: 'What do feature flags buy, and what do they cost?',
      answer: 'Deploy separated from release, and instant rollback. They cost combinatorial complexity and stale branches.',
      why: 'Every live flag doubles the paths through the code, and untested combinations are where the bugs hide. Flags need an owner and a removal date, or they become permanent configuration nobody understands.',
      difficulty: 'medium',
    },
    {
      id: 'prac-blameless-postmortem',
      question: 'Why are postmortems blameless?',
      answer: 'Because blame makes people hide information, and the information is the only thing of value.',
      why: 'If an engineer can cause an outage with one command, the finding is that the system allowed it, not that they typed it. Blame produces a culprit; blamelessness produces a guardrail.',
      difficulty: 'medium',
    },
    {
      id: 'prac-observability',
      question: 'What is the difference between monitoring and observability?',
      answer: 'Monitoring answers questions you knew to ask; observability lets you ask new ones after the fact.',
      why: 'A dashboard of known metrics cannot explain a failure mode nobody predicted. High-cardinality structured events — request id, user, version — let you slice the data at three in the morning against a question you have only just thought of.',
      difficulty: 'hard',
    },
    {
      id: 'prac-log-levels',
      question: 'What distinguishes a WARN from an ERROR in a log?',
      answer: 'ERROR means something failed and someone should look; WARN means something unexpected that the system handled.',
      why: 'The discipline matters because alerting keys off it. Logging every retry as ERROR produces a channel nobody reads, which is functionally the same as having no alerting at all.',
      difficulty: 'easy',
    },
    {
      id: 'prac-secrets',
      question: 'A secret was committed and then removed in a later commit. What now?',
      answer: 'Rotate it. It is still in history, and on every clone and fork.',
      why: 'Rewriting history does not recall the copies, and if the repository was ever public assume it was scraped within minutes. Removing it from history is housekeeping; rotation is the fix.',
      difficulty: 'medium',
    },
    {
      id: 'prac-least-privilege',
      question: 'What does least privilege mean in practice?',
      answer: 'Every component gets exactly the access it needs, and no more — including your own tooling.',
      why: 'It does not prevent compromise; it bounds it. The difference between a leaked read-only key and a leaked admin key is the difference between an incident and a catastrophe.',
      difficulty: 'medium',
    },
  ],
);
