import { deck } from './deck';

/**
 * React, aimed at the mental model rather than the API surface. Most React bugs
 * are one of three misunderstandings: what a render is, what a dependency array
 * means, and what state is allowed to be derived from.
 */
export const reactDeck = deck(
  'react',
  'React',
  'Renders, effects, keys, and derived state.',
  [
    {
      id: 'react-render-is',
      question: 'What does "render" mean in React?',
      answer: 'Calling your component function to produce a description of the UI. It is not a DOM update.',
      why: 'React then compares that description to the last one and touches only the DOM nodes that differ. A re-render with an identical result costs a function call and nothing else — which is why most "unnecessary re-render" panic is misplaced.',
      difficulty: 'easy',
    },
    {
      id: 'react-state-snapshot',
      question: 'Why does reading state right after setting it give the old value?',
      answer: 'State is a snapshot for that render. The variable will not change until the next one.',
      why: '`setCount(count + 1)` twice in a row increments once, because both read the same snapshot. The updater form `setCount(c => c + 1)` reads the pending value and composes correctly.',
      difficulty: 'medium',
    },
    {
      id: 'react-derived-state',
      question: 'When should something be state rather than computed during render?',
      answer: 'Only when it cannot be derived from existing props or state.',
      why: 'Storing a filtered list in state means it can disagree with the list it came from, and now needs an effect to keep it in step. Computing it during render makes disagreement impossible. Reach for `useMemo` only if the computation is genuinely expensive.',
      difficulty: 'medium',
    },
    {
      id: 'react-effect-purpose',
      question: 'What is `useEffect` actually for?',
      answer: 'Synchronising with something outside React — a subscription, a timer, the document title, a non-React widget.',
      why: 'It is not a lifecycle hook and not the place to transform data for rendering. An effect that only sets state from other state is a render-time computation wearing a costume, and it renders twice to reach the same answer.',
      difficulty: 'medium',
    },
    {
      id: 'react-effect-deps',
      question: 'What does an empty dependency array actually claim?',
      answer: 'That the effect uses nothing from the render that can change — so it runs once on mount.',
      why: 'When the effect does close over changing values, the empty array is a lie and it will read stale ones forever. The lint rule is right far more often than the developer overriding it.',
      difficulty: 'medium',
    },
    {
      id: 'react-effect-cleanup',
      question: 'What is the cleanup function for, and when does it run?',
      answer: 'Undoing what the effect set up. It runs before the effect re-runs and on unmount.',
      why: 'Without it, subscriptions and intervals accumulate on every dependency change. It is also the fix for the async race: a flag or AbortController in cleanup stops a slow response from overwriting a newer one.',
      difficulty: 'medium',
    },
    {
      id: 'react-strict-mode',
      question: 'Why does React 18 in development mount, unmount and remount every component?',
      answer: 'StrictMode deliberately double-invokes to surface effects that are not idempotent or lack cleanup.',
      why: 'A doubled network request or a duplicated subscription in development is the warning that the same bug exists in production the moment the component remounts for any other reason. The fix is cleanup, not disabling StrictMode.',
      difficulty: 'hard',
    },
    {
      id: 'react-key-index',
      question: 'Why is the array index a bad `key` for a reorderable list?',
      answer: 'The key identifies which item a piece of state belongs to. Indexes shift, so state follows position rather than data.',
      why: 'Delete the first row and every input\'s value moves up one. Index keys are fine only for a list that never reorders, filters or removes — which is rarer than it seems.',
      difficulty: 'medium',
    },
    {
      id: 'react-key-remount',
      question: 'What happens when you change a component\'s `key`?',
      answer: 'React discards the old instance and mounts a fresh one, resetting all its state.',
      why: 'That makes `key` a deliberate tool: keying a form on the record id resets it cleanly when the record changes — which is much simpler than an effect that clears every field.',
      difficulty: 'medium',
    },
    {
      id: 'react-mutation',
      question: 'Why does pushing to a state array not re-render?',
      answer: 'React compares by reference, and mutating in place leaves the reference identical.',
      why: 'Same for objects. Always produce a new value: `setItems([...items, next])`. This is also why the mutating array methods are the ones to memorise — push, splice and sort are the usual culprits.',
      difficulty: 'easy',
    },
    {
      id: 'react-usememo-when',
      question: 'When is `useMemo` actually worth it?',
      answer: 'For genuinely expensive computation, or to keep a stable reference that something downstream depends on.',
      why: 'It is not free — it costs a dependency comparison and memory, and every dependency array is a chance to be wrong. Wrapping a trivial calculation makes the code harder to read and measurably slower.',
      difficulty: 'medium',
    },
    {
      id: 'react-memo-breaks',
      question: 'Why does `React.memo` often fail to prevent a re-render?',
      answer: 'A new object, array or inline function prop is a fresh reference every render, so the shallow comparison always fails.',
      why: 'Memoising the child without stabilising the props is the most common wasted optimisation in React. The props need `useCallback`/`useMemo` too — which is a lot of machinery, and usually a sign the render was not the problem.',
      difficulty: 'hard',
    },
    {
      id: 'react-usecallback',
      question: 'What does `useCallback` do?',
      answer: 'Returns the same function reference between renders while its dependencies are unchanged.',
      why: 'Only useful when the identity matters — a memoised child, or an effect dependency. Wrapping every handler is cargo cult: a plain function passed to a DOM element costs nothing.',
      difficulty: 'medium',
    },
    {
      id: 'react-useref',
      question: 'What are the two distinct uses of `useRef`?',
      answer: 'Holding a DOM node, and holding a mutable value that must not trigger a re-render.',
      why: 'The second is the underused one — a timer id, a previous value, a "has this already run" flag. Changing `.current` never re-renders, which is exactly why it must not hold anything the UI displays.',
      difficulty: 'medium',
    },
    {
      id: 'react-context-rerender',
      question: 'What is the performance trap in Context?',
      answer: 'Every consumer re-renders when the value changes, and an inline object literal makes a new value every render.',
      why: 'Memoise the provider value. For a context mixing rarely-changing config with frequently-changing state, split it in two — otherwise one fast-moving field re-renders every consumer of the slow-moving ones.',
      difficulty: 'hard',
    },
    {
      id: 'react-context-purpose',
      question: 'What is Context for, and what is it not?',
      answer: 'For avoiding prop drilling of stable, widely-needed values. Not a state manager.',
      why: 'Theme, locale, the current user, a store instance. It has no selectors, so any consumer re-renders on any change — which is why high-frequency state belongs in something with subscriptions instead.',
      difficulty: 'medium',
    },
    {
      id: 'react-lifting-state',
      question: 'What is the rule for where state should live?',
      answer: 'In the closest common ancestor of every component that reads it — and no higher.',
      why: 'Too low and siblings cannot share it. Too high and unrelated subtrees re-render and the component becomes a switchboard. Most "we need Redux" moments are actually state that drifted too far up.',
      difficulty: 'easy',
    },
    {
      id: 'react-controlled',
      question: 'What makes an input controlled, and what breaks it?',
      answer: 'Its value comes from state with an onChange to update it. Passing a value with no onChange makes it read-only.',
      why: 'Switching between undefined and a value mid-life produces React\'s "changing an uncontrolled input to be controlled" warning. Initialise to an empty string, not undefined.',
      difficulty: 'easy',
    },
    {
      id: 'react-batching',
      question: 'What changed about state batching in React 18?',
      answer: 'Updates are now batched everywhere, including inside promises, timeouts and native handlers.',
      why: 'Before 18, only React event handlers batched, so two setState calls in a `.then()` caused two renders. Automatic batching removed a whole category of surprise — and occasionally exposed code that relied on the intermediate render.',
      difficulty: 'hard',
    },
    {
      id: 'react-suspense',
      question: 'What does `<Suspense>` do?',
      answer: 'Shows a fallback while a child is suspended, and renders the children once ready.',
      why: 'It moves the loading state from inside each component to a boundary around a region, so a group of components can appear together rather than as a cascade of individual spinners.',
      difficulty: 'medium',
    },
    {
      id: 'react-error-boundary',
      question: 'What can an error boundary not catch?',
      answer: 'Errors in event handlers, in async code, during server rendering, and in the boundary itself.',
      why: 'It catches errors thrown during rendering, in lifecycle methods and in constructors — the render path. Everything else needs an ordinary try/catch, which surprises people who expect it to be a global net.',
      difficulty: 'hard',
    },
    {
      id: 'react-hook-rules',
      question: 'Why must hooks not be called conditionally?',
      answer: 'React identifies them by call order, not by name. A skipped call shifts every subsequent hook onto the wrong state.',
      why: 'There is no registry mapping names to state — just an array walked in order. That single implementation fact explains the whole rule, including why an early return before a hook is equally fatal.',
      difficulty: 'medium',
    },
    {
      id: 'react-fetch-effect',
      question: 'What is wrong with fetching data in a bare `useEffect`?',
      answer: 'No caching, no deduplication, races on fast prop changes, a request waterfall, and no retry.',
      why: 'Each of those is fixable by hand and all of them together are a library. That is what React Query, SWR and framework loaders exist for — the effect is not wrong so much as the beginning of a long list.',
      difficulty: 'medium',
    },
    {
      id: 'react-list-state-reset',
      question: 'A modal keeps its previous content when opened for a different item. Why?',
      answer: 'It was never unmounted, so its state persisted. React reuses the instance at the same position.',
      why: 'Either key it on the item id to force a remount, or drive it entirely from props. The general rule: state survives as long as the component stays in the same place in the tree with the same key.',
      difficulty: 'hard',
    },
    {
      id: 'react-portal',
      question: 'Where do events from a portal bubble to?',
      answer: 'Up the React tree, not the DOM tree.',
      why: 'So a modal rendered into `document.body` still fires the click handler of its React parent. It is usually what you want and occasionally very confusing when a document-level listener also sees the event.',
      difficulty: 'hard',
    },
  ],
);
