import { deck } from './deck';

/**
 * The command line and regular expressions — the two tools that stay useful
 * whatever language the job is in, and the two most people learn by copying.
 */
export const shellDeck = deck(
  'shell',
  'Shell & regex',
  'Pipes, quoting, exit codes, and the regex that bites.',
  [
    {
      id: 'shell-quote',
      question: 'What is the difference between single and double quotes in the shell?',
      answer: 'Single quotes are literal. Double quotes still expand variables, command substitution and backticks.',
      why: 'It is why `echo "$HOME"` prints your path and `echo \'$HOME\'` prints the text. Almost every "it worked in my terminal but not in the script" is a quoting difference.',
      difficulty: 'easy',
    },
    {
      id: 'shell-unquoted-var',
      question: 'Why should `$var` almost always be written `"$var"`?',
      answer: 'Unquoted, it undergoes word splitting and glob expansion — so a path with a space becomes two arguments.',
      why: 'It is the single most common shell bug and it only shows up when a filename contains a space or an asterisk. `rm $file` on "my notes.txt" tries to delete two files, neither of which is the one you meant.',
      difficulty: 'medium',
    },
    {
      id: 'shell-exit-code',
      question: 'What does an exit code of 0 mean?',
      answer: 'Success. Any non-zero value is a failure, and the specific number is the program\'s own signal.',
      why: 'Backwards from most truthiness conventions, which is why `if command; then` reads oddly at first. It is also what `&&` and `||` branch on, and what CI uses to decide whether a step passed.',
      difficulty: 'easy',
    },
    {
      id: 'shell-pipefail',
      question: 'Why does `set -e` alone not make a script safe?',
      answer: 'A pipeline\'s exit code is its last command, so a failure earlier in the pipe is invisible.',
      why: '`curl bad-url | jq .` succeeds because jq succeeded. `set -euo pipefail` is the usual trio: exit on error, error on unset variables, and fail a pipeline if any stage failed.',
      difficulty: 'hard',
    },
    {
      id: 'shell-stdout-stderr',
      question: 'What is the difference between `2>&1` and `>&2`?',
      answer: 'The first sends stderr to wherever stdout currently goes; the second sends output to stderr.',
      why: 'Order matters: `cmd > file 2>&1` puts both in the file, but `cmd 2>&1 > file` sends stderr to the terminal, because the duplication happened before stdout was redirected.',
      difficulty: 'hard',
    },
    {
      id: 'shell-pipe-buffering',
      question: 'Why does a command\'s output appear immediately in the terminal but stall when piped?',
      answer: 'Many programs line-buffer to a terminal and block-buffer to a pipe.',
      why: 'The output is sitting in a 4KB buffer, not lost. `stdbuf -oL`, `unbuffer`, or the program\'s own flag (`grep --line-buffered`, `python -u`) restores line buffering.',
      difficulty: 'hard',
    },
    {
      id: 'shell-xargs',
      question: 'What problem do `find -print0` and `xargs -0` solve together?',
      answer: 'Filenames containing spaces or newlines, which ordinary whitespace splitting breaks on.',
      why: 'A null byte is the one character a filename cannot contain, so it is the only safe separator. Without it, "my file.txt" arrives as two arguments — the same class of bug as an unquoted variable.',
      difficulty: 'medium',
    },
    {
      id: 'shell-grep-r',
      question: 'What does `grep -rn "foo" .` do that plain `grep` does not?',
      answer: 'Recurses into directories and prints line numbers.',
      why: 'Add `-i` for case-insensitive and `-l` for filenames only. Worth knowing that ripgrep does this faster and respects .gitignore by default, which is usually what you wanted.',
      difficulty: 'easy',
    },
    {
      id: 'shell-tail-f',
      question: 'What is the difference between `tail -f` and `tail -F`?',
      answer: '`-f` follows the file handle; `-F` follows the filename and survives rotation.',
      why: 'When logrotate moves the file, `-f` keeps reading the old inode and appears to go silent forever. `-F` reopens the new file. This is why a log tail "stops working" at midnight.',
      difficulty: 'medium',
    },
    {
      id: 'shell-chmod-numbers',
      question: 'What does `chmod 644` mean?',
      answer: 'Owner read+write, group read, others read. Each digit is read 4, write 2, execute 1, summed.',
      why: '755 is the same plus execute for everyone — the normal setting for a directory or a script. 777 is almost always wrong and is a security finding in any review.',
      difficulty: 'easy',
    },
    {
      id: 'shell-path',
      question: 'What does `PATH` control, and why does order matter?',
      answer: 'Where the shell looks for executables. The first match wins.',
      why: 'It is why two versions of a tool can be installed and the wrong one runs. `which -a node` shows every match in order. Putting `.` in PATH is a classic hazard — a file called `ls` in a downloaded folder then runs instead of the real one.',
      difficulty: 'medium',
    },
    {
      id: 'shell-source-vs-run',
      question: 'Why does running a script that sets an environment variable not change your shell?',
      answer: 'It runs in a child process, and a child cannot alter its parent\'s environment.',
      why: '`source script.sh` (or `. script.sh`) runs it in the current shell instead, which is why activation scripts for virtual environments must be sourced.',
      difficulty: 'medium',
    },
    {
      id: 'shell-signals',
      question: 'What is the difference between SIGTERM and SIGKILL?',
      answer: 'TERM asks the process to shut down and can be handled; KILL cannot be caught and stops it immediately.',
      why: 'Reaching for `kill -9` first skips every cleanup handler — flushing buffers, releasing locks, finishing a request. Send TERM, wait, and escalate only if it hangs. This is exactly what a container runtime does on stop.',
      difficulty: 'medium',
    },
    {
      id: 'shell-jobs',
      question: 'Why does a background job die when you close the terminal, and how do you prevent it?',
      answer: 'It receives SIGHUP. `nohup`, `disown`, or a terminal multiplexer like tmux prevents it.',
      why: 'The signal means "the terminal hung up". For anything long-running on a remote machine, tmux or screen is the reliable answer, because it also survives your connection dropping mid-command.',
      difficulty: 'medium',
    },
    {
      id: 'regex-greedy',
      question: 'Why does `<.*>` match too much in `<a><b>`?',
      answer: '`*` is greedy — it takes everything, then backtracks to the last `>`.',
      why: 'Use the lazy `<.*?>`, or better the negated class `<[^>]*>`, which cannot overrun in the first place and needs no backtracking. The negated character class is almost always the faster and clearer fix.',
      difficulty: 'medium',
    },
    {
      id: 'regex-anchors',
      question: 'What do `^` and `$` mean, and what changes them?',
      answer: 'Start and end of the string. With the multiline flag they mean start and end of a line.',
      why: 'Forgetting to anchor a validation pattern is a security bug: an unanchored pattern matches anywhere, so a check for a safe value passes on a string that merely contains one somewhere.',
      difficulty: 'medium',
    },
    {
      id: 'regex-char-class',
      question: 'Inside `[...]`, which characters are still special?',
      answer: 'Very few — mainly `^` at the start, `-` between characters, and `]` and `\\`.',
      why: 'So `[.*+]` matches a literal dot, star or plus with no escaping. Putting `-` first or last makes it literal, which is how `[a-z-]` works.',
      difficulty: 'medium',
    },
    {
      id: 'regex-capture-group',
      question: 'What is the difference between `(...)` and `(?:...)`?',
      answer: 'The first captures the match for later use; the second groups without capturing.',
      why: 'Non-capturing groups keep the numbering of the groups you care about stable and avoid the cost of recording matches you will not read. Named groups `(?<year>...)` are better still — position-independent and self-documenting.',
      difficulty: 'medium',
    },
    {
      id: 'regex-lookahead',
      question: 'What does a lookahead like `(?=...)` do?',
      answer: 'Asserts what follows without consuming it, so the match position does not advance.',
      why: 'It is how "a password containing a digit and a letter" is expressed as several independent assertions at one position. Negative lookahead `(?!...)` is the same in reverse and is how you say "not followed by".',
      difficulty: 'hard',
    },
    {
      id: 'regex-catastrophic',
      question: 'What is catastrophic backtracking?',
      answer: 'Nested quantifiers over overlapping alternatives making the engine try exponentially many paths on a near-match.',
      why: 'A pattern like `(a+)+$` against a long string of a\'s hangs a thread forever. It is a real denial-of-service vector — ReDoS — whenever a regex meets user input. Avoid nesting quantifiers, and prefer specific character classes.',
      difficulty: 'hard',
    },
    {
      id: 'regex-dot',
      question: 'What does `.` not match by default?',
      answer: 'A newline.',
      why: 'Which is why a pattern that works on one line fails on a multi-line block. The dotall flag (`s`) makes it match everything. Note this is a different flag from multiline, which changes the anchors instead — the two are routinely confused.',
      difficulty: 'medium',
    },
    {
      id: 'regex-email',
      question: 'Why is validating an email address with a regex a bad idea?',
      answer: 'The grammar is far more permissive than anyone expects, so strict patterns reject valid addresses.',
      why: 'Check for an @ with something on both sides, then send a confirmation message. Deliverability is the only real validation, and it also catches the typo a perfect regex would happily accept.',
      difficulty: 'medium',
    },
    {
      id: 'regex-word-boundary',
      question: 'What does `\\b` match?',
      answer: 'A zero-width position between a word character and a non-word character.',
      why: 'It is what makes `\\bcat\\b` match "cat" but not "category". Because "word character" means `[A-Za-z0-9_]`, it behaves surprisingly around accented letters and other scripts.',
      difficulty: 'medium',
    },
    {
      id: 'regex-parse-html',
      question: 'Why can a regex not parse HTML?',
      answer: 'HTML nests arbitrarily deeply, and regular expressions cannot count.',
      why: 'Regular languages have no memory of how many tags are open. A regex can scrape a predictable fragment, and will silently produce wrong answers on the first comment, CDATA block or attribute containing a bracket. Use a parser.',
      difficulty: 'medium',
    },
    {
      id: 'shell-history-expansion',
      question: 'Why can a `!` inside a double-quoted string break an interactive bash command?',
      answer: 'History expansion runs before quoting is considered, in interactive shells.',
      why: '`echo "hello!"` can fail with "event not found". Single quotes avoid it, and it does not happen in scripts, where history expansion is off by default — another reason the terminal and the script disagree.',
      difficulty: 'hard',
    },
  ],
);
