import { deck } from './deck';

/**
 * SQL and relational databases — joins, indexes, transactions, and the handful
 * of things that turn a fast query into a slow one.
 */
export const sqlDeck = deck(
  'sql',
  'SQL & databases',
  'Joins, indexes, transactions, isolation.',
  [
    {
      id: 'sql-inner-left',
      question: 'What is the difference between an INNER JOIN and a LEFT JOIN?',
      answer: 'Inner keeps only rows matching on both sides; left keeps every left row, filling the right with NULLs.',
      why: 'The usual bug is a LEFT JOIN with a condition on the right table in the WHERE clause — that discards the NULL rows and silently turns it back into an inner join. The condition belongs in the ON clause.',
      difficulty: 'easy',
    },
    {
      id: 'sql-where-having',
      question: 'What is the difference between WHERE and HAVING?',
      answer: 'WHERE filters rows before grouping; HAVING filters groups after aggregation.',
      why: 'So you cannot reference an aggregate in WHERE, and filtering in HAVING what could have been filtered in WHERE means aggregating rows you were going to throw away. Filter early.',
      difficulty: 'easy',
    },
    {
      id: 'sql-null-comparison',
      question: 'Why does `WHERE column != \'x\'` skip rows where the column is NULL?',
      answer: 'Any comparison with NULL yields UNKNOWN, not true, and WHERE keeps only true.',
      why: 'NULL means unknown, so "is the unknown value not x" is itself unknown. You need `IS NULL` / `IS NOT NULL`, or `WHERE column IS DISTINCT FROM \'x\'`. This is the single most common source of quietly missing rows.',
      difficulty: 'medium',
    },
    {
      id: 'sql-count-null',
      question: 'How do `COUNT(*)`, `COUNT(col)` and `COUNT(DISTINCT col)` differ?',
      answer: 'Rows; non-NULL values of col; distinct non-NULL values of col.',
      why: 'The gap between the first two is exactly the number of NULLs, which makes it a quick data-quality check. Aggregates other than COUNT(*) all skip NULLs, so an AVG over a column with missing data averages fewer rows than you think.',
      difficulty: 'medium',
    },
    {
      id: 'sql-index-when',
      question: 'When does an index make things worse?',
      answer: 'On write-heavy tables, on low-cardinality columns, and when the query returns a large fraction of the table.',
      why: 'Every index must be updated on insert, update and delete. And a planner will correctly ignore an index if it estimates a scan is cheaper — reading half the table via an index means random I/O for every row.',
      difficulty: 'medium',
    },
    {
      id: 'sql-composite-order',
      question: 'Why does the column order in a composite index matter?',
      answer: 'It can only be used for prefixes — an index on (a, b) helps queries on a, and on a+b, but not on b alone.',
      why: 'Think of a phone book sorted by surname then first name: useless for finding every "James". Put the equality-filtered, high-selectivity column first, and the range or sort column after it.',
      difficulty: 'hard',
    },
    {
      id: 'sql-sargable',
      question: 'Why does `WHERE YEAR(created_at) = 2026` not use the index on created_at?',
      answer: 'Wrapping the column in a function means the stored values no longer match what is being compared.',
      why: 'The predicate is not sargable. Rewrite as a range — `created_at >= \'2026-01-01\' AND created_at < \'2027-01-01\'` — which the index can seek. Alternatively index the expression itself, where the database supports that.',
      difficulty: 'hard',
    },
    {
      id: 'sql-covering-index',
      question: 'What is a covering index?',
      answer: 'One containing every column the query needs, so the table itself is never read.',
      why: 'It turns two lookups into one: the index seek is the whole answer. This is why `SELECT *` can be dramatically slower than selecting the three columns you need — the star defeats the covering index.',
      difficulty: 'hard',
    },
    {
      id: 'sql-explain',
      question: 'What is the first thing to look for in an EXPLAIN plan?',
      answer: 'A sequential scan on a large table, and a large gap between estimated and actual rows.',
      why: 'The estimate gap is the more useful signal: it means the statistics are stale, and every choice the planner made downstream was based on a bad number. `ANALYZE` refreshes them.',
      difficulty: 'medium',
    },
    {
      id: 'sql-acid',
      question: 'What does ACID stand for?',
      answer: 'Atomicity, Consistency, Isolation, Durability.',
      why: 'Atomicity is all-or-nothing; consistency is that constraints hold at commit; isolation is how much concurrent transactions can see of each other; durability is that a commit survives a crash. Isolation is the one with dials on it.',
      difficulty: 'easy',
    },
    {
      id: 'sql-isolation-levels',
      question: 'What does READ COMMITTED still allow that REPEATABLE READ does not?',
      answer: 'Non-repeatable reads — the same row read twice in one transaction can differ.',
      why: 'Read committed only guarantees you never see uncommitted data. It is the default in PostgreSQL and SQL Server, which surprises people who assume a transaction gives them a stable snapshot. It does not, unless you ask for one.',
      difficulty: 'hard',
    },
    {
      id: 'sql-phantom',
      question: 'What is a phantom read?',
      answer: 'A second identical range query returns rows that were not there before, because another transaction inserted them.',
      why: 'Repeatable read protects rows you already read but not rows that appear. Only SERIALIZABLE prevents it, and it does so by being prepared to abort transactions — so serialisable code must be written to retry.',
      difficulty: 'hard',
    },
    {
      id: 'sql-lost-update',
      question: 'Why is read-modify-write in application code unsafe under concurrency?',
      answer: 'Two transactions read the same value, both compute from it, and the second write erases the first.',
      why: 'The lost update. Fix it in one statement — `SET count = count + 1` — or with `SELECT ... FOR UPDATE`, or with an optimistic version column checked in the WHERE clause of the update.',
      difficulty: 'medium',
    },
    {
      id: 'sql-deadlock',
      question: 'What causes a database deadlock and what is the standard prevention?',
      answer: 'Two transactions taking the same locks in opposite orders. Prevented by always locking in a consistent order.',
      why: 'The database detects the cycle and kills one transaction, so the application must be ready to retry. Consistent ordering — for instance always by primary key ascending — removes most of them.',
      difficulty: 'hard',
    },
    {
      id: 'sql-transaction-scope',
      question: 'Why should a transaction never contain a network call?',
      answer: 'It holds locks for the duration of something that can hang, blocking other writers and exhausting the pool.',
      why: 'A payment API that takes thirty seconds becomes a thirty-second lock. Do the external work outside, and keep the transaction to the writes — this is the ordinary version of the same reasoning behind the saga pattern.',
      difficulty: 'medium',
    },
    {
      id: 'sql-injection',
      question: 'Why do parameterised queries stop SQL injection when escaping does not reliably?',
      answer: 'The query and the data travel separately, so data is never parsed as SQL.',
      why: 'Escaping is a string operation that has to be perfect against every encoding and dialect quirk. Parameterisation removes the category — the parser sees the statement before it ever sees the value. It is also usually faster, because plans get reused.',
      difficulty: 'medium',
    },
    {
      id: 'sql-normalisation',
      question: 'What is third normal form, informally?',
      answer: 'Every non-key column depends on the key, the whole key, and nothing but the key.',
      why: 'It removes the update anomalies that come from storing the same fact twice. Deliberate denormalisation is then a performance decision made knowingly — with the duplication documented and a plan for keeping the copies in step.',
      difficulty: 'medium',
    },
    {
      id: 'sql-fk-value',
      question: 'What does a foreign key constraint buy that application checks do not?',
      answer: 'A guarantee that holds against every writer, including scripts, migrations and the console.',
      why: 'Application-level checks are enforced only by the code paths that remember to. The database is the last place the invariant can actually be true, which is why "we validate in the app" leaves orphaned rows in every mature system.',
      difficulty: 'medium',
    },
    {
      id: 'sql-uuid-pk',
      question: 'What is the cost of a random UUID as a primary key?',
      answer: 'Inserts scatter across the index instead of appending, causing page splits and poor cache behaviour.',
      why: 'It is a real but often overstated cost, and it is why time-ordered variants — UUIDv7, ULID — exist: they keep global uniqueness while inserting in roughly sequential order.',
      difficulty: 'hard',
    },
    {
      id: 'sql-soft-delete',
      question: 'What does soft deletion cost?',
      answer: 'Every query must remember the filter, unique constraints stop working, and the table grows forever.',
      why: 'A missed `WHERE deleted_at IS NULL` shows deleted data as live. Worth it when you genuinely need recovery or audit; often an archive table is the cleaner answer.',
      difficulty: 'medium',
    },
    {
      id: 'sql-window-function',
      question: 'What can a window function do that GROUP BY cannot?',
      answer: 'Compute an aggregate across a set of rows while keeping every individual row.',
      why: 'Running totals, per-row rank, and "compare this row to its group average" all become one pass. The classic use is `ROW_NUMBER() OVER (PARTITION BY x ORDER BY y)` to take the latest row per group without a self-join.',
      difficulty: 'hard',
    },
    {
      id: 'sql-cte',
      question: 'What is a CTE good for beyond readability?',
      answer: 'Recursion — walking trees and graphs stored as parent references.',
      why: 'A `WITH RECURSIVE` query traverses an org chart or a category tree in one statement. Be aware that in some databases a CTE is an optimisation fence, so it is not always free relative to a subquery.',
      difficulty: 'hard',
    },
    {
      id: 'sql-migration-safety',
      question: 'Why can adding a NOT NULL column with a default lock a large table?',
      answer: 'Older engines rewrote the whole table to fill in the value.',
      why: 'Modern PostgreSQL and MySQL avoid the rewrite for a constant default, but the safe general pattern is still: add nullable, backfill in batches, then add the constraint. Long locks in a migration are how a deploy becomes an outage.',
      difficulty: 'hard',
    },
    {
      id: 'sql-connection-pool',
      question: 'Why does raising the connection pool size often make a database slower?',
      answer: 'Beyond the point where cores and disk are saturated, more concurrency means more contention and context switching.',
      why: 'Queueing in the pool is usually cheaper than queueing inside the database, where connections hold locks and memory. Pool sizes in the low tens typically outperform hundreds.',
      difficulty: 'hard',
    },
    {
      id: 'sql-replica-lag',
      question: 'What breaks when you send reads to a replica?',
      answer: 'Read-your-writes. A user saves something and the next read from a lagging replica does not have it yet.',
      why: 'The usual fixes are routing reads to the primary for a short window after a write, or waiting on a replication position. Assuming replicas are current is the bug that only appears under load, when lag grows.',
      difficulty: 'hard',
    },
  ],
);
