import { deck } from './deck';

/**
 * TypeScript as a type system rather than as annotations — the distinctions
 * that decide whether the compiler is helping you or being argued with.
 */
export const typescriptDeck = deck(
  'typescript',
  'TypeScript',
  'Structural typing, narrowing, and the escape hatches.',
  [
    {
      id: 'ts-structural',
      question: 'Is TypeScript structurally or nominally typed?',
      answer: 'Structurally — compatibility is decided by shape, not by name or declared inheritance.',
      why: 'Any object with the right members satisfies an interface without ever mentioning it. This is why two unrelated types with identical fields are interchangeable, and why "branding" a type with a private or phantom field is the trick used to make it behave nominally.',
      difficulty: 'medium',
    },
    {
      id: 'ts-any-unknown',
      question: 'What is the difference between `any` and `unknown`?',
      answer: '`any` disables checking; `unknown` accepts anything but permits nothing until you narrow it.',
      why: '`any` is contagious — it silently spreads through every expression it touches and switches the compiler off. `unknown` is the honest version of "I do not know yet": it forces a check at the boundary, which is exactly where a check belongs.',
      difficulty: 'easy',
    },
    {
      id: 'ts-never',
      question: 'What does `never` mean, and where does it show up usefully?',
      answer: 'A value that cannot exist. Most usefully in exhaustiveness checks on a union.',
      why: 'Assigning the switch variable to a `never` in the default branch makes the compiler fail if a union member is ever added and not handled. It turns "I added a case to the enum" from a runtime surprise into a build error.',
      difficulty: 'medium',
    },
    {
      id: 'ts-type-interface',
      question: 'When does it matter whether you use `type` or `interface`?',
      answer: 'Interfaces can be reopened and merged; type aliases cannot, but can express unions, tuples and mapped types.',
      why: 'Declaration merging is the real difference — it is why library augmentation uses interfaces. For everything you own, either works; pick one and be consistent. Only a type alias can say `type Result = Ok | Err`.',
      difficulty: 'easy',
    },
    {
      id: 'ts-narrowing',
      question: 'What is narrowing?',
      answer: 'The compiler shrinking a value\'s type inside a branch based on a check you wrote.',
      why: 'A `typeof x === "string"` guard, a truthiness check, an `in` operator, or a discriminant comparison all narrow. It is the mechanism that makes unions ergonomic instead of a cast at every use.',
      difficulty: 'easy',
    },
    {
      id: 'ts-discriminated-union',
      question: 'What is a discriminated union and why is it the workhorse pattern?',
      answer: 'A union whose members share a literal-typed field, so checking that field narrows to exactly one member.',
      why: '`{ status: "ok", data: T } | { status: "error", message: string }` lets the compiler prove `data` exists only in the ok branch. It replaces the optional-fields-everywhere shape where every access needs a `!`.',
      difficulty: 'medium',
    },
    {
      id: 'ts-type-predicate',
      question: 'What does the return type `x is Foo` do?',
      answer: 'Declares a user-defined type guard — a boolean function whose truth narrows the argument at the call site.',
      why: 'Without it, a helper that returns boolean tells the compiler nothing, and you narrow again inside every caller. With it, `if (isFoo(v))` narrows `v`. The catch: it is an assertion, so a wrong implementation lies to the compiler silently.',
      difficulty: 'medium',
    },
    {
      id: 'ts-as-const',
      question: 'What does `as const` do?',
      answer: 'Makes the literal deeply readonly and infers the narrowest literal types instead of widening.',
      why: '`const a = ["x", "y"]` infers `string[]`; `as const` makes it `readonly ["x", "y"]`. That is what lets you derive a union from an array with `typeof arr[number]`, keeping the values and the type in one place.',
      difficulty: 'medium',
    },
    {
      id: 'ts-satisfies',
      question: 'What does `satisfies` give you that a type annotation does not?',
      answer: 'It checks the value against a type without widening the inferred type to it.',
      why: 'Annotating a config as `Record<string, string>` checks it but loses the specific keys. `satisfies Record<string, string>` checks it and keeps the literal key names, so `config.apiUrl` still autocompletes and misspellings still fail.',
      difficulty: 'hard',
    },
    {
      id: 'ts-generic-constraint',
      question: 'What does `<T extends { id: string }>` express?',
      answer: 'A constraint — T can be any type, provided it has a string `id`.',
      why: 'Without the constraint the body cannot touch `.id`, because T might be a number. Constraints are how a generic stays generic while still being usable, and `extends` here means "assignable to", not class inheritance.',
      difficulty: 'medium',
    },
    {
      id: 'ts-keyof',
      question: 'What is `keyof T`?',
      answer: 'The union of T\'s property names as literal types.',
      why: 'Paired with a generic it gives type-safe property access: `get<T, K extends keyof T>(obj: T, key: K): T[K]`. The compiler then knows the return type varies with the key you passed, rather than being a union of all of them.',
      difficulty: 'medium',
    },
    {
      id: 'ts-utility-types',
      question: 'What do `Partial`, `Pick`, `Omit` and `Required` do?',
      answer: 'Make every field optional; keep named fields; drop named fields; make every field required.',
      why: 'They are all built from mapped types and are how you derive one shape from another rather than declaring it twice. `Omit` is the one to watch: it takes any string, so a typo in the omitted key compiles silently and omits nothing.',
      difficulty: 'easy',
    },
    {
      id: 'ts-record',
      question: 'What is the risk of typing a lookup as `Record<string, Foo>`?',
      answer: 'Every access is typed as Foo, including the misses — the type claims a value exists for every string.',
      why: 'It hides the undefined. Turning on `noUncheckedIndexedAccess` makes indexed reads `Foo | undefined`, which is the truth. Otherwise prefer a Map, or a Record over a literal union of keys where the compiler knows the whole domain.',
      difficulty: 'hard',
    },
    {
      id: 'ts-strict-null',
      question: 'What does `strictNullChecks` change?',
      answer: 'null and undefined stop being assignable to every type and must be handled explicitly.',
      why: 'Without it, every type silently includes null, so the compiler can never warn about the most common runtime error there is. It is the single highest-value flag in the config, and the reason `strict: true` is the default advice.',
      difficulty: 'easy',
    },
    {
      id: 'ts-non-null-assert',
      question: 'What does the `!` postfix operator actually do?',
      answer: 'Nothing at runtime — it only tells the compiler to stop worrying.',
      why: 'It is a claim you are making, not a check being performed. If you are wrong you get the same crash you would have got in JavaScript, minus the warning. Fine when you can see the invariant a few lines up; a smell when it is sprinkled everywhere.',
      difficulty: 'easy',
    },
    {
      id: 'ts-erasure',
      question: 'What happens to types at runtime?',
      answer: 'They are erased entirely. The emitted JavaScript has no trace of them.',
      why: 'So you cannot check a type at runtime, cannot switch on a generic parameter, and cannot trust data crossing a boundary because the compiler never saw it. Anything from a network, a file or a form needs a real validator — the annotation is a promise, not a check.',
      difficulty: 'medium',
    },
    {
      id: 'ts-enum',
      question: 'Why do many codebases avoid `enum` in favour of a union of string literals?',
      answer: 'Enums emit real runtime objects and are nominally typed; a literal union is erased and structural.',
      why: '`type Status = "open" | "closed"` costs nothing at runtime, works directly with JSON, and any matching string satisfies it. `const enum` erases too but breaks under isolated module transpilation, which most build tools now use.',
      difficulty: 'medium',
    },
    {
      id: 'ts-readonly',
      question: 'Does `readonly` prevent mutation at runtime?',
      answer: 'No — it is compile-time only, and a readonly array can be passed where a mutable one is expected via a cast.',
      why: 'It documents and enforces intent within type-checked code, which is most of its value. For real immutability you need `Object.freeze`, and even that is shallow.',
      difficulty: 'medium',
    },
    {
      id: 'ts-unknown-catch',
      question: 'What type does a caught error have under modern settings?',
      answer: '`unknown`, because anything can be thrown — not just Error.',
      why: '`useUnknownInCatchVariables` reflects reality: `throw "boom"` is legal. So narrow before use, typically with `err instanceof Error ? err.message : String(err)`.',
      difficulty: 'medium',
    },
    {
      id: 'ts-variance-params',
      question: 'Why does TypeScript allow a handler taking a supertype where one taking a subtype is expected?',
      answer: 'Method parameters are checked bivariantly for historical compatibility; standalone function types are contravariant under `strictFunctionTypes`.',
      why: 'It is a deliberate unsoundness kept because the DOM and array APIs depend on it. Worth knowing when a callback type mismatch either does or does not error depending on whether it was declared as a method or a property.',
      difficulty: 'hard',
    },
    {
      id: 'ts-declaration-files',
      question: 'What is a `.d.ts` file for?',
      answer: 'Declaring types for code the compiler cannot see — plain JavaScript, globals, or non-code imports.',
      why: 'It carries types and no implementation. This is how `@types/*` packages work, and how you tell the compiler that importing a `.svg` yields a string or that `window.myGlobal` exists.',
      difficulty: 'medium',
    },
    {
      id: 'ts-module-resolution',
      question: 'What does `moduleResolution` control?',
      answer: 'How the compiler turns an import specifier into a file on disk.',
      why: 'It is the setting behind most "cannot find module" errors that have nothing to do with the module being missing. Modern bundler setups want `"bundler"`; Node ESM wants `"node16"`/`"nodenext"`, which enforces file extensions in relative imports.',
      difficulty: 'hard',
    },
    {
      id: 'ts-infer-return',
      question: 'Should you annotate the return type of every function?',
      answer: 'On exported and public functions, usually yes. On small internal ones, inference is fine.',
      why: 'An explicit return type turns a change in the body into an error at that function rather than at the twelve call sites downstream. It also stops a leaked `any` from propagating silently, and keeps the compiler faster on large files.',
      difficulty: 'easy',
    },
    {
      id: 'ts-index-signature-vs-map',
      question: 'Why can you not use an object type with an index signature to model a fixed set of keys?',
      answer: 'An index signature says "any key of this kind is allowed", which discards the exact key names.',
      why: 'You lose autocomplete, typo detection and exhaustiveness. When the key set is known, write the literal type or derive it with a mapped type over a union — reserve index signatures for genuinely open dictionaries.',
      difficulty: 'medium',
    },
    {
      id: 'ts-generic-default',
      question: 'What does `<T = string>` mean on a generic?',
      answer: 'A default type argument, used when the caller does not supply or the compiler cannot infer one.',
      why: 'It keeps a generic API usable without turning every call into `fn<Something>()`. Note that a default is not a constraint — use `<T extends string = string>` when you need both.',
      difficulty: 'medium',
    },
  ],
);
